/**
==============================================================================
Copyright (C) 2019 - Philip Paquette, Steven Bocco

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License along
 with this program.  If not, see <https:www.gnu.org/licenses/>.
==============================================================================
**/
export const SvgAncMedExtra = {
    "jdipNS:DISPLAY":{
        "jdipNS:ZOOM":{
            "min":"5",
            "max":"250",
            "factor":"1.2"
        },
        "jdipNS:LABELS":{
            "brief":"true",
            "full":"false"
        }
    },
    "jdipNS:ORDERDRAWING":{
        "jdipNS:POWERCOLORS":{
            "jdipNS:POWERCOLOR":[
                {
                    "power":"rome",
                    "color":"red"
                },
                {
                    "power":"carthage",
                    "color":"blue"
                },
                {
                    "power":"persia",
                    "color":"black"
                },
                {
                    "power":"greece",
                    "color":"forestgreen"
                },
                {
                    "power":"egypt",
                    "color":"yellow"
                }
            ]
        },
        "jdipNS:SYMBOLSIZE":[
            {
                "name":"Fleet",
                "width":"20",
                "height":"20"
            },
            {
                "name":"Army",
                "width":"20",
                "height":"20"
            },
            {
                "name":"Wing",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedFleet",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedArmy",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedWing",
                "width":"20",
                "height":"20"
            },
            {
                "name":"FailedOrder",
                "width":"20",
                "height":"20"
            },
            {
                "name":"SupplyCenter",
                "width":"10",
                "height":"10"
            },
            {
                "name":"BuildUnit",
                "width":"30",
                "height":"30"
            },
            {
                "name":"RemoveUnit",
                "width":"30",
                "height":"30"
            },
            {
                "name":"WaivedBuild",
                "width":"25",
                "height":"25"
            }
        ],
        "jdipNS:BUILD":{
            "deltaRadius":"0"
        },
        "jdipNS:REMOVE":{
            "deltaRadius":"5"
        },
        "jdipNS:DISBAND":{
            "deltaRadius":"5"
        },
        "jdipNS:WAIVE":{
            "deltaRadius":"0"
        },
        "jdipNS:HOLD":{
            "deltaRadius":"5",
            "strokeCSSStyle":"varwidthorder",
            "highlightOffset":"0",
            "highlightCSSClass":"varwidthshadow",
            "widths":"6,9,12,18",
            "shadowWidths":"10,15,20,25"
        },
        "jdipNS:MOVE":{
            "deltaRadius":"5",
            "strokeCSSStyle":"varwidthorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"varwidthshadow",
            "widths":"6,9,12,18",
            "shadowWidths":"10,15,20,25"
        },
        "jdipNS:RETREAT":{
            "deltaRadius":"5",
            "strokeCSSStyle":"defaultorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"shadoworder"
        },
        "jdipNS:SUPPORT":{
            "deltaRadius":"10",
            "strokeCSSStyle":"supportorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"shadowdash"
        },
        "jdipNS:CONVOY":{
            "deltaRadius":"10",
            "strokeCSSStyle":"convoyorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"shadowdash"
        }
    },
    "jdipNS:PROVINCE_DATA":{
        "jdipNS:PROVINCE":[
            {
                "jdipNS:UNIT":{
                    "x":"484",
                    "y":"211"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"489",
                    "y":"206"
                },
                "name":"adr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"669",
                    "y":"345"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"674",
                    "y":"340"
                },
                "name":"aeg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"717",
                    "y":"514"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"722",
                    "y":"509"
                },
                "name":"ale"
            },
            {
                "jdipNS:UNIT":{
                    "x":"923",
                    "y":"314"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"928",
                    "y":"309"
                },
                "name":"ant"
            },
            {
                "jdipNS:UNIT":{
                    "x":"455",
                    "y":"232"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"460",
                    "y":"227"
                },
                "name":"apu"
            },
            {
                "jdipNS:UNIT":{
                    "x":"983",
                    "y":"426"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"988",
                    "y":"421"
                },
                "name":"ara"
            },
            {
                "jdipNS:UNIT":{
                    "x":"989",
                    "y":"224"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"994",
                    "y":"219"
                },
                "name":"arm"
            },
            {
                "jdipNS:UNIT":{
                    "x":"593",
                    "y":"310"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"598",
                    "y":"305"
                },
                "name":"ath"
            },
            {
                "jdipNS:UNIT":{
                    "x":"497",
                    "y":"392"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"502",
                    "y":"387"
                },
                "name":"aus"
            },
            {
                "jdipNS:UNIT":{
                    "x":"165",
                    "y":"250"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"170",
                    "y":"245"
                },
                "name":"bal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"694",
                    "y":"627"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"699",
                    "y":"622"
                },
                "name":"bay"
            },
            {
                "jdipNS:UNIT":{
                    "x":"217",
                    "y":"325"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"222",
                    "y":"320"
                },
                "name":"ber"
            },
            {
                "jdipNS:UNIT":{
                    "x":"771",
                    "y":"219"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"776",
                    "y":"214"
                },
                "name":"bit"
            },
            {
                "jdipNS:UNIT":{
                    "x":"782",
                    "y":"153"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"787",
                    "y":"148"
                },
                "name":"bla"
            },
            {
                "jdipNS:UNIT":{
                    "x":"694",
                    "y":"252"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"699",
                    "y":"247"
                },
                "name":"byz"
            },
            {
                "jdipNS:UNIT":{
                    "x":"877",
                    "y":"279"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"882",
                    "y":"274"
                },
                "name":"cap"
            },
            {
                "jdipNS:UNIT":{
                    "x":"315",
                    "y":"382"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"320",
                    "y":"377"
                },
                "name":"car"
            },
            {
                "jdipNS:UNIT":{
                    "x":"893",
                    "y":"69"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"898",
                    "y":"64"
                },
                "name":"che"
            },
            {
                "jdipNS:UNIT":{
                    "x":"797",
                    "y":"363"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"802",
                    "y":"358"
                },
                "name":"cil"
            },
            {
                "jdipNS:UNIT":{
                    "x":"248",
                    "y":"452"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"253",
                    "y":"447"
                },
                "name":"cir"
            },
            {
                "jdipNS:UNIT":{
                    "x":"319",
                    "y":"225"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"324",
                    "y":"220"
                },
                "name":"cor"
            },
            {
                "jdipNS:UNIT":{
                    "x":"662",
                    "y":"392"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"667",
                    "y":"387"
                },
                "name":"cre"
            },
            {
                "jdipNS:UNIT":{
                    "x":"842",
                    "y":"378"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"847",
                    "y":"373"
                },
                "name":"cyp"
            },
            {
                "jdipNS:UNIT":{
                    "x":"637",
                    "y":"518"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"642",
                    "y":"513"
                },
                "name":"cyr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"633",
                    "y":"148"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"638",
                    "y":"143"
                },
                "name":"dac"
            },
            {
                "jdipNS:UNIT":{
                    "x":"514",
                    "y":"188"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"519",
                    "y":"183"
                },
                "name":"dal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"985",
                    "y":"318"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"990",
                    "y":"313"
                },
                "name":"dam"
            },
            {
                "jdipNS:UNIT":{
                    "x":"740",
                    "y":"451"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"745",
                    "y":"446"
                },
                "name":"egy"
            },
            {
                "jdipNS:UNIT":{
                    "x":"556",
                    "y":"277"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"561",
                    "y":"272"
                },
                "name":"epi"
            },
            {
                "jdipNS:UNIT":{
                    "x":"325",
                    "y":"139"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"330",
                    "y":"134"
                },
                "name":"etr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"786",
                    "y":"274"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"791",
                    "y":"269"
                },
                "name":"gal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"209",
                    "y":"93"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"214",
                    "y":"88"
                },
                "name":"gau"
            },
            {
                "jdipNS:UNIT":{
                    "x":"855",
                    "y":"456"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"860",
                    "y":"451"
                },
                "name":"gop"
            },
            {
                "jdipNS:UNIT":{
                    "x":"521",
                    "y":"508"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"526",
                    "y":"503"
                },
                "name":"gos"
            },
            {
                "jdipNS:UNIT":{
                    "x":"487",
                    "y":"438"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"492",
                    "y":"433"
                },
                "name":"got"
            },
            {
                "jdipNS:UNIT":{
                    "x":"94",
                    "y":"366"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"99",
                    "y":"361"
                },
                "name":"ibe"
            },
            {
                "jdipNS:UNIT":{
                    "x":"548",
                    "y":"167"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"553",
                    "y":"162"
                },
                "name":"ill"
            },
            {
                "jdipNS:UNIT":{
                    "x":"520",
                    "y":"316"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"525",
                    "y":"311"
                },
                "name":"ion"
            },
            {
                "jdipNS:UNIT":{
                    "x":"818",
                    "y":"323"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"823",
                    "y":"318"
                },
                "name":"isa"
            },
            {
                "jdipNS:UNIT":{
                    "x":"911",
                    "y":"461"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"916",
                    "y":"456"
                },
                "name":"jer"
            },
            {
                "jdipNS:UNIT":{
                    "x":"480",
                    "y":"543"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"485",
                    "y":"538"
                },
                "name":"lep"
            },
            {
                "jdipNS:UNIT":{
                    "x":"556",
                    "y":"438"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"561",
                    "y":"433"
                },
                "name":"lib"
            },
            {
                "jdipNS:UNIT":{
                    "x":"268",
                    "y":"225"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"273",
                    "y":"220"
                },
                "name":"lig"
            },
            {
                "jdipNS:UNIT":{
                    "x":"30",
                    "y":"237"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"35",
                    "y":"232"
                },
                "name":"lus"
            },
            {
                "jdipNS:UNIT":{
                    "x":"623",
                    "y":"241"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"628",
                    "y":"236"
                },
                "name":"mac"
            },
            {
                "jdipNS:UNIT":{
                    "x":"613",
                    "y":"571"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"618",
                    "y":"566"
                },
                "name":"mar"
            },
            {
                "jdipNS:UNIT":{
                    "x":"265",
                    "y":"137"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"270",
                    "y":"132"
                },
                "name":"mas"
            },
            {
                "jdipNS:UNIT":{
                    "x":"124",
                    "y":"420"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"129",
                    "y":"415"
                },
                "name":"mau"
            },
            {
                "jdipNS:UNIT":{
                    "x":"795",
                    "y":"564"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"800",
                    "y":"559"
                },
                "name":"mem"
            },
            {
                "jdipNS:UNIT":{
                    "x":"547",
                    "y":"388"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"552",
                    "y":"383"
                },
                "name":"mes"
            },
            {
                "jdipNS:UNIT":{
                    "x":"742",
                    "y":"323"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"747",
                    "y":"318"
                },
                "name":"mil"
            },
            {
                "jdipNS:UNIT":{
                    "x":"721",
                    "y":"380"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"726",
                    "y":"375"
                },
                "name":"min"
            },
            {
                "jdipNS:UNIT":{
                    "x":"988",
                    "y":"538"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"993",
                    "y":"533"
                },
                "name":"nab"
            },
            {
                "jdipNS:UNIT":{
                    "x":"469",
                    "y":"284"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"474",
                    "y":"279"
                },
                "name":"nea"
            },
            {
                "jdipNS:UNIT":{
                    "x":"355",
                    "y":"481"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"360",
                    "y":"476"
                },
                "name":"num"
            },
            {
                "jdipNS:UNIT":{
                    "x":"929",
                    "y":"518"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"934",
                    "y":"513"
                },
                "name":"pet"
            },
            {
                "jdipNS:UNIT":{
                    "x":"412",
                    "y":"563"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"417",
                    "y":"558"
                },
                "name":"pha"
            },
            {
                "jdipNS:UNIT":{
                    "x":"370",
                    "y":"348"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"375",
                    "y":"343"
                },
                "name":"pun"
            },
            {
                "jdipNS:UNIT":{
                    "x":"403",
                    "y":"179"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"408",
                    "y":"174"
                },
                "name":"rav"
            },
            {
                "jdipNS:UNIT":{
                    "x":"962",
                    "y":"604"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"967",
                    "y":"599"
                },
                "name":"ree"
            },
            {
                "jdipNS:UNIT":{
                    "x":"351",
                    "y":"69"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"356",
                    "y":"64"
                },
                "name":"rha"
            },
            {
                "jdipNS:UNIT":{
                    "x":"380",
                    "y":"198"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"385",
                    "y":"193"
                },
                "name":"rom"
            },
            {
                "jdipNS:UNIT":{
                    "x":"70",
                    "y":"312"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"75",
                    "y":"307"
                },
                "name":"sag"
            },
            {
                "jdipNS:UNIT":{
                    "x":"281",
                    "y":"598"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"286",
                    "y":"593"
                },
                "name":"sah"
            },
            {
                "jdipNS:UNIT":{
                    "x":"316",
                    "y":"274"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"321",
                    "y":"269"
                },
                "name":"sad"
            },
            {
                "jdipNS:UNIT":{
                    "x":"529",
                    "y":"66"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"534",
                    "y":"61"
                },
                "name":"sam"
            },
            {
                "jdipNS:UNIT":{
                    "x":"433",
                    "y":"343"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"438",
                    "y":"338"
                },
                "name":"sic"
            },
            {
                "jdipNS:UNIT":{
                    "x":"931",
                    "y":"365"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"936",
                    "y":"360"
                },
                "name":"sid"
            },
            {
                "jdipNS:UNIT":{
                    "x":"883",
                    "y":"500"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"888",
                    "y":"495"
                },
                "name":"sin"
            },
            {
                "jdipNS:UNIT":{
                    "x":"877",
                    "y":"206"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"882",
                    "y":"201"
                },
                "name":"sip"
            },
            {
                "jdipNS:UNIT":{
                    "x":"595",
                    "y":"332"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"600",
                    "y":"327"
                },
                "name":"spa"
            },
            {
                "jdipNS:UNIT":{
                    "x":"876",
                    "y":"412"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"881",
                    "y":"407"
                },
                "name":"syr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"140",
                    "y":"231"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"145",
                    "y":"226"
                },
                "name":"tar"
            },
            {
                "jdipNS:UNIT":{
                    "x":"319",
                    "y":"429"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"324",
                    "y":"424"
                },
                "name":"tha"
            },
            {
                "jdipNS:UNIT":{
                    "x":"891",
                    "y":"601"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"896",
                    "y":"596"
                },
                "name":"thb"
            },
            {
                "jdipNS:UNIT":{
                    "x":"926",
                    "y":"393"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"931",
                    "y":"388"
                },
                "name":"tye"
            },
            {
                "jdipNS:UNIT":{
                    "x":"407",
                    "y":"278"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"412",
                    "y":"273"
                },
                "name":"tyn"
            },
            {
                "jdipNS:UNIT":{
                    "x":"358",
                    "y":"110"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"363",
                    "y":"105"
                },
                "name":"ven"
            },
            {
                "jdipNS:UNIT":{
                    "x":"422",
                    "y":"81"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"427",
                    "y":"76"
                },
                "name":"vin"
            }
        ]
    }
};
            