/**
==============================================================================
Copyright (C) 2019 - Philip Paquette, Steven Bocco

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License along
 with this program.  If not, see <https:www.gnu.org/licenses/>.
==============================================================================
**/
export const SvgAncMedExtra = {
    "jdipNS:DISPLAY":{
        "jdipNS:ZOOM":{
            "min":"5",
            "max":"250",
            "factor":"1.2"
        },
        "jdipNS:LABELS":{
            "brief":"true",
            "full":"false"
        }
    },
    "jdipNS:ORDERDRAWING":{
        "jdipNS:POWERCOLORS":{
            "jdipNS:POWERCOLOR":[
                {
                    "power":"rome",
                    "color":"#c48f85"
                },
                {
                    "power":"carthage",
                    "color":"royalblue"
                },
                {
                    "power":"persia",
                    "color":"gray"
                },
                {
                    "power":"greece",
                    "color":"forestgreen"
                },
                {
                    "power":"egypt",
                    "color":"#b9a61c"
                }
            ]
        },
        "jdipNS:SYMBOLSIZE":[
            {
                "name":"Fleet",
                "width":"20",
                "height":"20"
            },
            {
                "name":"Army",
                "width":"20",
                "height":"20"
            },
            {
                "name":"Wing",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedFleet",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedArmy",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedWing",
                "width":"20",
                "height":"20"
            },
            {
                "name":"FailedOrder",
                "width":"20",
                "height":"20"
            },
            {
                "name":"SupplyCenter",
                "width":"10",
                "height":"10"
            },
            {
                "name":"BuildUnit",
                "width":"30",
                "height":"30"
            },
            {
                "name":"RemoveUnit",
                "width":"30",
                "height":"30"
            },
            {
                "name":"WaivedBuild",
                "width":"25",
                "height":"25"
            },
            {
                "name":"HoldUnit",
                "width":"40",
                "height":"40"
            },
            {
                "name":"SupportHoldUnit",
                "width":"46",
                "height":"46"
            },
            {
                "name":"ConvoyTriangle",
                "width":"50",
                "height":"43.2"
            },
            {
                "name":"Stroke",
                "width":"3",
                "height":"5"
            }
        ]
    },
    "jdipNS:PROVINCE_DATA":{
        "jdipNS:PROVINCE":[
            {
                "jdipNS:UNIT":{
                    "x":"472.5",
                    "y":"201.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"479.5",
                    "y":"194.0"
                },
                "name":"adr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"657.5",
                    "y":"335.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"664.5",
                    "y":"328.0"
                },
                "name":"aeg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"705.5",
                    "y":"504.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"712.5",
                    "y":"497.0"
                },
                "name":"ale"
            },
            {
                "jdipNS:UNIT":{
                    "x":"911.5",
                    "y":"304.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"918.5",
                    "y":"297.0"
                },
                "name":"ant"
            },
            {
                "jdipNS:UNIT":{
                    "x":"443.5",
                    "y":"222.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"450.5",
                    "y":"215.0"
                },
                "name":"apu"
            },
            {
                "jdipNS:UNIT":{
                    "x":"971.5",
                    "y":"416.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"978.5",
                    "y":"409.0"
                },
                "name":"ara"
            },
            {
                "jdipNS:UNIT":{
                    "x":"977.5",
                    "y":"214.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"984.5",
                    "y":"207.0"
                },
                "name":"arm"
            },
            {
                "jdipNS:UNIT":{
                    "x":"581.5",
                    "y":"300.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"588.5",
                    "y":"293.0"
                },
                "name":"ath"
            },
            {
                "jdipNS:UNIT":{
                    "x":"485.5",
                    "y":"382.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"492.5",
                    "y":"375.0"
                },
                "name":"aus"
            },
            {
                "jdipNS:UNIT":{
                    "x":"153.5",
                    "y":"240.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"160.5",
                    "y":"233.0"
                },
                "name":"bal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"682.5",
                    "y":"617.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"689.5",
                    "y":"610.0"
                },
                "name":"bay"
            },
            {
                "jdipNS:UNIT":{
                    "x":"205.5",
                    "y":"315.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"212.5",
                    "y":"308.0"
                },
                "name":"ber"
            },
            {
                "jdipNS:UNIT":{
                    "x":"759.5",
                    "y":"209.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"766.5",
                    "y":"202.0"
                },
                "name":"bit"
            },
            {
                "jdipNS:UNIT":{
                    "x":"770.5",
                    "y":"143.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"777.5",
                    "y":"136.0"
                },
                "name":"bla"
            },
            {
                "jdipNS:UNIT":{
                    "x":"682.5",
                    "y":"242.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"689.5",
                    "y":"235.0"
                },
                "name":"byz"
            },
            {
                "jdipNS:UNIT":{
                    "x":"865.5",
                    "y":"269.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"872.5",
                    "y":"262.0"
                },
                "name":"cap"
            },
            {
                "jdipNS:UNIT":{
                    "x":"303.5",
                    "y":"372.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"310.5",
                    "y":"365.0"
                },
                "name":"car"
            },
            {
                "jdipNS:UNIT":{
                    "x":"881.5",
                    "y":"59.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"888.5",
                    "y":"52.0"
                },
                "name":"che"
            },
            {
                "jdipNS:UNIT":{
                    "x":"785.5",
                    "y":"353.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"792.5",
                    "y":"346.0"
                },
                "name":"cil"
            },
            {
                "jdipNS:UNIT":{
                    "x":"236.5",
                    "y":"442.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"243.5",
                    "y":"435.0"
                },
                "name":"cir"
            },
            {
                "jdipNS:UNIT":{
                    "x":"307.5",
                    "y":"215.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"314.5",
                    "y":"208.0"
                },
                "name":"cor"
            },
            {
                "jdipNS:UNIT":{
                    "x":"650.5",
                    "y":"382.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"657.5",
                    "y":"375.0"
                },
                "name":"cre"
            },
            {
                "jdipNS:UNIT":{
                    "x":"816.5",
                    "y":"374.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"823.5",
                    "y":"367.0"
                },
                "name":"cyp"
            },
            {
                "jdipNS:UNIT":{
                    "x":"625.5",
                    "y":"508.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"632.5",
                    "y":"501.0"
                },
                "name":"cyr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"621.5",
                    "y":"138.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"628.5",
                    "y":"131.0"
                },
                "name":"dac"
            },
            {
                "jdipNS:UNIT":{
                    "x":"502.5",
                    "y":"178.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"509.5",
                    "y":"171.0"
                },
                "name":"dal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"973.5",
                    "y":"308.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"980.5",
                    "y":"301.0"
                },
                "name":"dam"
            },
            {
                "jdipNS:UNIT":{
                    "x":"728.5",
                    "y":"441.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"735.5",
                    "y":"434.0"
                },
                "name":"egy"
            },
            {
                "jdipNS:UNIT":{
                    "x":"544.5",
                    "y":"267.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"551.5",
                    "y":"260.0"
                },
                "name":"epi"
            },
            {
                "jdipNS:UNIT":{
                    "x":"313.5",
                    "y":"129.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"320.5",
                    "y":"122.0"
                },
                "name":"etr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"774.5",
                    "y":"264.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"781.5",
                    "y":"257.0"
                },
                "name":"gal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"197.5",
                    "y":"83.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"204.5",
                    "y":"76.0"
                },
                "name":"gau"
            },
            {
                "jdipNS:UNIT":{
                    "x":"843.5",
                    "y":"446.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"850.5",
                    "y":"439.0"
                },
                "name":"gop"
            },
            {
                "jdipNS:UNIT":{
                    "x":"509.5",
                    "y":"498.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"516.5",
                    "y":"491.0"
                },
                "name":"gos"
            },
            {
                "jdipNS:UNIT":{
                    "x":"475.5",
                    "y":"428.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"482.5",
                    "y":"421.0"
                },
                "name":"got"
            },
            {
                "jdipNS:UNIT":{
                    "x":"82.5",
                    "y":"356.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"89.5",
                    "y":"349.0"
                },
                "name":"ibe"
            },
            {
                "jdipNS:UNIT":{
                    "x":"536.5",
                    "y":"157.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"543.5",
                    "y":"150.0"
                },
                "name":"ill"
            },
            {
                "jdipNS:UNIT":{
                    "x":"508.5",
                    "y":"306.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"515.5",
                    "y":"299.0"
                },
                "name":"ion"
            },
            {
                "jdipNS:UNIT":{
                    "x":"806.5",
                    "y":"313.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"813.5",
                    "y":"306.0"
                },
                "name":"isa"
            },
            {
                "jdipNS:UNIT":{
                    "x":"899.5",
                    "y":"451.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"906.5",
                    "y":"444.0"
                },
                "name":"jer"
            },
            {
                "jdipNS:UNIT":{
                    "x":"468.5",
                    "y":"533.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"475.5",
                    "y":"526.0"
                },
                "name":"lep"
            },
            {
                "jdipNS:UNIT":{
                    "x":"544.5",
                    "y":"428.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"551.5",
                    "y":"421.0"
                },
                "name":"lib"
            },
            {
                "jdipNS:UNIT":{
                    "x":"256.5",
                    "y":"215.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"263.5",
                    "y":"208.0"
                },
                "name":"lig"
            },
            {
                "jdipNS:UNIT":{
                    "x":"18.5",
                    "y":"227.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"25.5",
                    "y":"220.0"
                },
                "name":"lus"
            },
            {
                "jdipNS:UNIT":{
                    "x":"611.5",
                    "y":"231.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"618.5",
                    "y":"224.0"
                },
                "name":"mac"
            },
            {
                "jdipNS:UNIT":{
                    "x":"601.5",
                    "y":"561.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"608.5",
                    "y":"554.0"
                },
                "name":"mar"
            },
            {
                "jdipNS:UNIT":{
                    "x":"253.5",
                    "y":"127.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"260.5",
                    "y":"120.0"
                },
                "name":"mas"
            },
            {
                "jdipNS:UNIT":{
                    "x":"112.5",
                    "y":"410.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"119.5",
                    "y":"403.0"
                },
                "name":"mau"
            },
            {
                "jdipNS:UNIT":{
                    "x":"783.5",
                    "y":"554.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"790.5",
                    "y":"547.0"
                },
                "name":"mem"
            },
            {
                "jdipNS:UNIT":{
                    "x":"535.5",
                    "y":"378.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"542.5",
                    "y":"371.0"
                },
                "name":"mes"
            },
            {
                "jdipNS:UNIT":{
                    "x":"730.5",
                    "y":"313.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"737.5",
                    "y":"306.0"
                },
                "name":"mil"
            },
            {
                "jdipNS:UNIT":{
                    "x":"709.5",
                    "y":"370.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"716.5",
                    "y":"363.0"
                },
                "name":"min"
            },
            {
                "jdipNS:UNIT":{
                    "x":"976.5",
                    "y":"528.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"983.5",
                    "y":"521.0"
                },
                "name":"nab"
            },
            {
                "jdipNS:UNIT":{
                    "x":"457.5",
                    "y":"274.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"464.5",
                    "y":"267.0"
                },
                "name":"nea"
            },
            {
                "jdipNS:UNIT":{
                    "x":"343.5",
                    "y":"471.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"350.5",
                    "y":"464.0"
                },
                "name":"num"
            },
            {
                "jdipNS:UNIT":{
                    "x":"917.5",
                    "y":"508.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"924.5",
                    "y":"501.0"
                },
                "name":"pet"
            },
            {
                "jdipNS:UNIT":{
                    "x":"400.5",
                    "y":"553.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"407.5",
                    "y":"546.0"
                },
                "name":"pha"
            },
            {
                "jdipNS:UNIT":{
                    "x":"358.5",
                    "y":"338.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"365.5",
                    "y":"331.0"
                },
                "name":"pun"
            },
            {
                "jdipNS:UNIT":{
                    "x":"391.5",
                    "y":"169.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"398.5",
                    "y":"162.0"
                },
                "name":"rav"
            },
            {
                "jdipNS:UNIT":{
                    "x":"950.5",
                    "y":"594.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"957.5",
                    "y":"587.0"
                },
                "name":"ree"
            },
            {
                "jdipNS:UNIT":{
                    "x":"339.5",
                    "y":"59.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"346.5",
                    "y":"52.0"
                },
                "name":"rha"
            },
            {
                "jdipNS:UNIT":{
                    "x":"368.5",
                    "y":"188.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"375.5",
                    "y":"181.0"
                },
                "name":"rom"
            },
            {
                "jdipNS:UNIT":{
                    "x":"304.5",
                    "y":"264.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"311.5",
                    "y":"257.0"
                },
                "name":"sad"
            },
            {
                "jdipNS:UNIT":{
                    "x":"58.5",
                    "y":"302.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"65.5",
                    "y":"295.0"
                },
                "name":"sag"
            },
            {
                "jdipNS:UNIT":{
                    "x":"269.5",
                    "y":"588.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"276.5",
                    "y":"581.0"
                },
                "name":"sah"
            },
            {
                "jdipNS:UNIT":{
                    "x":"517.5",
                    "y":"56.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"524.5",
                    "y":"49.0"
                },
                "name":"sam"
            },
            {
                "jdipNS:UNIT":{
                    "x":"421.5",
                    "y":"333.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"428.5",
                    "y":"326.0"
                },
                "name":"sic"
            },
            {
                "jdipNS:UNIT":{
                    "x":"919.5",
                    "y":"355.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"926.5",
                    "y":"348.0"
                },
                "name":"sid"
            },
            {
                "jdipNS:UNIT":{
                    "x":"871.5",
                    "y":"490.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"878.5",
                    "y":"483.0"
                },
                "name":"sin"
            },
            {
                "jdipNS:UNIT":{
                    "x":"865.5",
                    "y":"196.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"872.5",
                    "y":"189.0"
                },
                "name":"sip"
            },
            {
                "jdipNS:UNIT":{
                    "x":"583.5",
                    "y":"322.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"590.5",
                    "y":"315.0"
                },
                "name":"spa"
            },
            {
                "jdipNS:UNIT":{
                    "x":"864.5",
                    "y":"402.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"871.5",
                    "y":"395.0"
                },
                "name":"syr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"128.5",
                    "y":"221.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"135.5",
                    "y":"214.0"
                },
                "name":"tar"
            },
            {
                "jdipNS:UNIT":{
                    "x":"307.5",
                    "y":"419.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"314.5",
                    "y":"412.0"
                },
                "name":"tha"
            },
            {
                "jdipNS:UNIT":{
                    "x":"879.5",
                    "y":"591.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"886.5",
                    "y":"584.0"
                },
                "name":"thb"
            },
            {
                "jdipNS:UNIT":{
                    "x":"914.5",
                    "y":"383.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"921.5",
                    "y":"376.0"
                },
                "name":"tye"
            },
            {
                "jdipNS:UNIT":{
                    "x":"395.5",
                    "y":"268.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"402.5",
                    "y":"261.0"
                },
                "name":"tyn"
            },
            {
                "jdipNS:UNIT":{
                    "x":"346.5",
                    "y":"100.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"353.5",
                    "y":"93.0"
                },
                "name":"ven"
            },
            {
                "jdipNS:UNIT":{
                    "x":"410.5",
                    "y":"71.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"417.5",
                    "y":"64.0"
                },
                "name":"vin"
            }
        ]
    }
};
            