/**
==============================================================================
Copyright (C) 2019 - Philip Paquette, Steven Bocco

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License along
 with this program.  If not, see <https:www.gnu.org/licenses/>.
==============================================================================
**/
export const SvgModernExtra = {
    "jdipNS:DISPLAY":{
        "jdipNS:ZOOM":{
            "min":"5",
            "max":"2200",
            "factor":"1.2"
        },
        "jdipNS:LABELS":{
            "brief":"true",
            "full":"false"
        }
    },
    "jdipNS:ORDERDRAWING":{
        "jdipNS:POWERCOLORS":{
            "jdipNS:POWERCOLOR":[
                {
                    "power":"Britain",
                    "color":"#0000FF"
                },
                {
                    "power":"Egypt",
                    "color":"#808000"
                },
                {
                    "power":"France",
                    "color":"#00FFFF"
                },
                {
                    "power":"Germany",
                    "color":"darkgrey"
                },
                {
                    "power":"Italy",
                    "color":"#80FF80"
                },
                {
                    "power":"Poland",
                    "color":"#FF0000"
                },
                {
                    "power":"Russia",
                    "color":"#008000"
                },
                {
                    "power":"Spain",
                    "color":"#FF8080"
                },
                {
                    "power":"Turkey",
                    "color":"#FFFF00"
                },
                {
                    "power":"Ukraine",
                    "color":"#FF00FF"
                }
            ]
        },
        "jdipNS:SYMBOLSIZE":[
            {
                "name":"Fleet",
                "width":"20",
                "height":"20"
            },
            {
                "name":"Army",
                "width":"20",
                "height":"20"
            },
            {
                "name":"Wing",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedFleet",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedArmy",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedWing",
                "width":"20",
                "height":"20"
            },
            {
                "name":"FailedOrder",
                "width":"17",
                "height":"17"
            },
            {
                "name":"SupplyCenter",
                "width":"10",
                "height":"10"
            },
            {
                "name":"BuildUnit",
                "width":"25",
                "height":"30"
            },
            {
                "name":"RemoveUnit",
                "width":"25",
                "height":"27"
            },
            {
                "name":"WaivedBuild",
                "width":"25",
                "height":"25"
            }
        ],
        "jdipNS:BUILD":{
            "deltaRadius":"0"
        },
        "jdipNS:REMOVE":{
            "deltaRadius":"5"
        },
        "jdipNS:DISBAND":{
            "deltaRadius":"5"
        },
        "jdipNS:WAIVE":{
            "deltaRadius":"0"
        },
        "jdipNS:HOLD":{
            "deltaRadius":"5",
            "strokeCSSStyle":"varwidthorder",
            "highlightOffset":"0",
            "highlightCSSClass":"varwidthshadow",
            "widths":"6,9,12,18",
            "shadowWidths":"10,15,20,25"
        },
        "jdipNS:MOVE":{
            "deltaRadius":"5",
            "strokeCSSStyle":"varwidthorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"varwidthshadow",
            "widths":"6,9,12,18",
            "shadowWidths":"10,15,20,25"
        },
        "jdipNS:RETREAT":{
            "deltaRadius":"5",
            "strokeCSSStyle":"defaultorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"shadoworder"
        },
        "jdipNS:SUPPORT":{
            "deltaRadius":"10",
            "strokeCSSStyle":"supportorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"shadowdash"
        },
        "jdipNS:CONVOY":{
            "deltaRadius":"10",
            "strokeCSSStyle":"convoyorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"shadowdash"
        }
    },
    "jdipNS:PROVINCE_DATA":{
        "jdipNS:PROVINCE":[
            {
                "jdipNS:UNIT":{
                    "x":"539.4",
                    "y":"366.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"546.4",
                    "y":"359.9"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"488.8",
                    "y":"400.5"
                },
                "name":"ada"
            },
            {
                "jdipNS:UNIT":{
                    "x":"288.3",
                    "y":"342.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"295.3",
                    "y":"335.9"
                },
                "name":"adr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"382.7",
                    "y":"395.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"389.7",
                    "y":"392.3"
                },
                "name":"aeg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"325.9",
                    "y":"360.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"332.9",
                    "y":"353.6"
                },
                "name":"alb"
            },
            {
                "jdipNS:UNIT":{
                    "x":"406.9",
                    "y":"511"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"413.9",
                    "y":"504"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"441.4",
                    "y":"472.7"
                },
                "name":"ale"
            },
            {
                "jdipNS:UNIT":{
                    "x":"141.9",
                    "y":"454.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"148.9",
                    "y":"447.2"
                },
                "name":"alg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"199.3",
                    "y":"248"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"206.3",
                    "y":"241"
                },
                "name":"als"
            },
            {
                "jdipNS:UNIT":{
                    "x":"466.8",
                    "y":"389"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"473.8",
                    "y":"382"
                },
                "name":"ana"
            },
            {
                "jdipNS:UNIT":{
                    "x":"94.6",
                    "y":"363.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"101.6",
                    "y":"356.8"
                },
                "name":"adl"
            },
            {
                "jdipNS:UNIT":{
                    "x":"466.8",
                    "y":"349.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"473.8",
                    "y":"342.1"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"461.2",
                    "y":"365.9"
                },
                "name":"ank"
            },
            {
                "jdipNS:UNIT":{
                    "x":"281",
                    "y":"355.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"288",
                    "y":"348.5"
                },
                "name":"apu"
            },
            {
                "jdipNS:UNIT":{
                    "x":"685.5",
                    "y":"530.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"692.5",
                    "y":"523.6"
                },
                "name":"ara"
            },
            {
                "jdipNS:UNIT":{
                    "x":"569.9",
                    "y":"324.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"576.9",
                    "y":"317.9"
                },
                "name":"arm"
            },
            {
                "jdipNS:UNIT":{
                    "x":"502.6",
                    "y":"546.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"509.6",
                    "y":"539.7"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"482.5",
                    "y":"542.7"
                },
                "name":"asw"
            },
            {
                "jdipNS:UNIT":{
                    "x":"260.4",
                    "y":"280.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"267.4",
                    "y":"272.5"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"287",
                    "y":"266"
                },
                "name":"aus"
            },
            {
                "jdipNS:UNIT":{
                    "x":"161.9",
                    "y":"296.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"168.9",
                    "y":"289.5"
                },
                "name":"auv"
            },
            {
                "jdipNS:UNIT":{
                    "x":"207.8",
                    "y":"15.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"214.8",
                    "y":"8.8"
                },
                "name":"arc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"595.1",
                    "y":"316.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"602.1",
                    "y":"309.5"
                },
                "name":"aze"
            },
            {
                "jdipNS:UNIT":{
                    "x":"321.5",
                    "y":"146.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"328.5",
                    "y":"139.4"
                },
                "name":"bal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"97.7",
                    "y":"249.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"104.7",
                    "y":"242.3"
                },
                "name":"bis"
            },
            {
                "jdipNS:UNIT":{
                    "x":"125.1",
                    "y":"332.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"132.1",
                    "y":"325.2"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"139.4",
                    "y":"331.9"
                },
                "name":"bar"
            },
            {
                "jdipNS:UNIT":{
                    "x":"298.6",
                    "y":"8.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"305.6",
                    "y":"1.4"
                },
                "name":"brn"
            },
            {
                "jdipNS:UNIT":{
                    "x":"189.3",
                    "y":"216.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"196.3",
                    "y":"209.8"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"204",
                    "y":"215"
                },
                "name":"bel"
            },
            {
                "jdipNS:UNIT":{
                    "x":"272.3",
                    "y":"188.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"279.3",
                    "y":"181.9"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"277.6",
                    "y":"208"
                },
                "name":"ber"
            },
            {
                "jdipNS:UNIT":{
                    "x":"377.5",
                    "y":"199.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"384.5",
                    "y":"192.8"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"405",
                    "y":"189"
                },
                "name":"bie"
            },
            {
                "jdipNS:UNIT":{
                    "x":"145.1",
                    "y":"288.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"152.1",
                    "y":"281.1"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"136.6",
                    "y":"279.6"
                },
                "name":"bor"
            },
            {
                "jdipNS:UNIT":{
                    "x":"275.6",
                    "y":"175.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"282.6",
                    "y":"168.6"
                },
                "name":"bhm"
            },
            {
                "jdipNS:UNIT":{
                    "x":"306.2",
                    "y":"317"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"313.2",
                    "y":"310"
                },
                "name":"bos"
            },
            {
                "jdipNS:UNIT":{
                    "x":"137.7",
                    "y":"242.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"144.7",
                    "y":"235.9"
                },
                "name":"bri"
            },
            {
                "jdipNS:UNIT":{
                    "x":"392.2",
                    "y":"332.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"399.2",
                    "y":"325.2"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"360.8",
                    "y":"343.2"
                },
                "name":"bul"
            },
            {
                "jdipNS:UNIT":{
                    "x":"486.8",
                    "y":"513.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"493.8",
                    "y":"506.1"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"471.1",
                    "y":"469.8"
                },
                "name":"cai"
            },
            {
                "jdipNS:UNIT":{
                    "x":"638.2",
                    "y":"321.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"645.2",
                    "y":"314.7"
                },
                "name":"cas"
            },
            {
                "jdipNS:UNIT":{
                    "x":"560.4",
                    "y":"279.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"567.4",
                    "y":"272.7"
                },
                "name":"cau"
            },
            {
                "jdipNS:UNIT":{
                    "x":"445.8",
                    "y":"193.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"452.8",
                    "y":"186.5"
                },
                "name":"crp"
            },
            {
                "jdipNS:UNIT":{
                    "x":"155.5",
                    "y":"104.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"162.5",
                    "y":"97.6"
                },
                "name":"cly"
            },
            {
                "jdipNS:UNIT":{
                    "x":"290.2",
                    "y":"291.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"297.2",
                    "y":"284.1"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"279.4",
                    "y":"298.2"
                },
                "name":"cro"
            },
            {
                "jdipNS:UNIT":{
                    "x":"275",
                    "y":"242"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"282",
                    "y":"235"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"293",
                    "y":"238"
                },
                "name":"cze"
            },
            {
                "jdipNS:UNIT":{
                    "x":"253.7",
                    "y":"147.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"260.7",
                    "y":"140.7"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"265.8",
                    "y":"168.5"
                },
                "name":"den"
            },
            {
                "jdipNS:UNIT":{
                    "x":"487.8",
                    "y":"251.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"494.8",
                    "y":"244.3"
                },
                "name":"don"
            },
            {
                "jdipNS:UNIT":{
                    "x":"484.7",
                    "y":"304.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"491.7",
                    "y":"297.9"
                },
                "name":"ebs"
            },
            {
                "jdipNS:UNIT":{
                    "x":"479.4",
                    "y":"440.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"486.4",
                    "y":"433.5"
                },
                "name":"eme"
            },
            {
                "jdipNS:UNIT":{
                    "x":"366.9",
                    "y":"485.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"373.9",
                    "y":"478.7"
                },
                "name":"esa"
            },
            {
                "jdipNS:UNIT":{
                    "x":"166.1",
                    "y":"114.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"173.1",
                    "y":"107.5"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"159.9",
                    "y":"141.7"
                },
                "name":"edi"
            },
            {
                "jdipNS:UNIT":{
                    "x":"83.1",
                    "y":"216.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"90.1",
                    "y":"209.8"
                },
                "name":"eng"
            },
            {
                "jdipNS:UNIT":{
                    "x":"371.2",
                    "y":"121.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"378.2",
                    "y":"114.2"
                },
                "name":"est"
            },
            {
                "jdipNS:UNIT":{
                    "x":"368",
                    "y":"72.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"375",
                    "y":"65.5"
                },
                "name":"fin"
            },
            {
                "jdipNS:UNIT":{
                    "x":"247.1",
                    "y":"216.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"254.1",
                    "y":"209.8"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"232.2",
                    "y":"242.2"
                },
                "name":"fra"
            },
            {
                "jdipNS:UNIT":{
                    "x":"337.4",
                    "y":"177.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"344.4",
                    "y":"170.6"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"324.7",
                    "y":"188"
                },
                "name":"gda"
            },
            {
                "jdipNS:UNIT":{
                    "x":"545.7",
                    "y":"308.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"552.7",
                    "y":"301.1"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"567",
                    "y":"310.8"
                },
                "name":"geo"
            },
            {
                "jdipNS:UNIT":{
                    "x":"62",
                    "y":"370.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"69",
                    "y":"363.1"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"56.7",
                    "y":"378"
                },
                "name":"gib"
            },
            {
                "jdipNS:UNIT":{
                    "x":"534.1",
                    "y":"103"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"541.1",
                    "y":"96"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"491.7",
                    "y":"103.5"
                },
                "name":"gor"
            },
            {
                "jdipNS:UNIT":{
                    "x":"347",
                    "y":"377.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"354",
                    "y":"370.5"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"360.8",
                    "y":"403.4"
                },
                "name":"gre"
            },
            {
                "jdipNS:UNIT":{
                    "x":"328.1",
                    "y":"107.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"335.1",
                    "y":"100.9"
                },
                "name":"gob"
            },
            {
                "jdipNS:UNIT":{
                    "x":"147.2",
                    "y":"356.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"154.2",
                    "y":"349.4"
                },
                "name":"gol"
            },
            {
                "jdipNS:UNIT":{
                    "x":"235.1",
                    "y":"198.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"242.1",
                    "y":"191.2"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"243.4",
                    "y":"192.7"
                },
                "name":"ham"
            },
            {
                "jdipNS:UNIT":{
                    "x":"229.8",
                    "y":"169"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"236.8",
                    "y":"162"
                },
                "name":"hel"
            },
            {
                "jdipNS:UNIT":{
                    "x":"213.9",
                    "y":"200.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"220.9",
                    "y":"193.2"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"212",
                    "y":"193"
                },
                "name":"hol"
            },
            {
                "jdipNS:UNIT":{
                    "x":"308.8",
                    "y":"285.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"315.8",
                    "y":"278.2"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"332",
                    "y":"273"
                },
                "name":"hun"
            },
            {
                "jdipNS:UNIT":{
                    "x":"125.1",
                    "y":"32.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"132.1",
                    "y":"25.6"
                },
                "name":"ice"
            },
            {
                "jdipNS:UNIT":{
                    "x":"314.4",
                    "y":"401.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"321.4",
                    "y":"394.6"
                },
                "name":"ion"
            },
            {
                "jdipNS:UNIT":{
                    "x":"581.4",
                    "y":"397.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"588.4",
                    "y":"390.4"
                },
                "name":"irk"
            },
            {
                "jdipNS:UNIT":{
                    "x":"636.1",
                    "y":"395.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"643.1",
                    "y":"388.3"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"663.5",
                    "y":"370.1"
                },
                "name":"irn"
            },
            {
                "jdipNS:UNIT":{
                    "x":"639.2",
                    "y":"357.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"675",
                    "y":"395"
                },
                "name":"irn-nc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"679.2",
                    "y":"446.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"675",
                    "y":"395"
                },
                "name":"irn-sc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"111.7",
                    "y":"143.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"118.7",
                    "y":"136.8"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"111.1",
                    "y":"161.5"
                },
                "name":"ire"
            },
            {
                "jdipNS:UNIT":{
                    "x":"108.3",
                    "y":"182.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"115.3",
                    "y":"175.3"
                },
                "name":"iri"
            },
            {
                "jdipNS:UNIT":{
                    "x":"505.7",
                    "y":"430"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"512.7",
                    "y":"423"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"506.5",
                    "y":"454.3"
                },
                "name":"isr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"434.2",
                    "y":"365.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"441.2",
                    "y":"358.9"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"405.4",
                    "y":"356.7"
                },
                "name":"ist"
            },
            {
                "jdipNS:UNIT":{
                    "x":"410",
                    "y":"391.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"417",
                    "y":"384.1"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"410.3",
                    "y":"406.9"
                },
                "name":"izm"
            },
            {
                "jdipNS:UNIT":{
                    "x":"523.6",
                    "y":"447.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"530.6",
                    "y":"440.9"
                },
                "name":"jor"
            },
            {
                "jdipNS:UNIT":{
                    "x":"656.1",
                    "y":"208.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"663.1",
                    "y":"201.2"
                },
                "name":"kaz"
            },
            {
                "jdipNS:UNIT":{
                    "x":"490",
                    "y":"232.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"497",
                    "y":"225.4"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"472.6",
                    "y":"230.8"
                },
                "name":"kha"
            },
            {
                "jdipNS:UNIT":{
                    "x":"439.5",
                    "y":"216.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"446.5",
                    "y":"209.6"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"417.4",
                    "y":"227.2"
                },
                "name":"kie"
            },
            {
                "jdipNS:UNIT":{
                    "x":"345.9",
                    "y":"231.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"352.9",
                    "y":"224.3"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"324.1",
                    "y":"245.8"
                },
                "name":"kra"
            },
            {
                "jdipNS:UNIT":{
                    "x":"323.8",
                    "y":"23.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"330.8",
                    "y":"16.1"
                },
                "name":"lap"
            },
            {
                "jdipNS:UNIT":{
                    "x":"346.7",
                    "y":"149.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"353.7",
                    "y":"142.7"
                },
                "name":"lat"
            },
            {
                "jdipNS:UNIT":{
                    "x":"313.3",
                    "y":"511"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"320.3",
                    "y":"504"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"238.4",
                    "y":"465.6"
                },
                "name":"lib"
            },
            {
                "jdipNS:UNIT":{
                    "x":"298.6",
                    "y":"460.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"305.6",
                    "y":"453.5"
                },
                "name":"lbn"
            },
            {
                "jdipNS:UNIT":{
                    "x":"206",
                    "y":"333"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"213",
                    "y":"326"
                },
                "name":"lig"
            },
            {
                "jdipNS:UNIT":{
                    "x":"360.6",
                    "y":"165"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"367.6",
                    "y":"158"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"375.9",
                    "y":"172.2"
                },
                "name":"lit"
            },
            {
                "jdipNS:UNIT":{
                    "x":"146.2",
                    "y":"139.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"153.2",
                    "y":"132.8"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"150.7",
                    "y":"170.7"
                },
                "name":"liv"
            },
            {
                "jdipNS:UNIT":{
                    "x":"174.1",
                    "y":"188.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"181.1",
                    "y":"181.9"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"162.8",
                    "y":"204.6"
                },
                "name":"lon"
            },
            {
                "jdipNS:UNIT":{
                    "x":"176",
                    "y":"274"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"183",
                    "y":"267"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"188.2",
                    "y":"273.2"
                },
                "name":"lyo"
            },
            {
                "jdipNS:UNIT":{
                    "x":"342.8",
                    "y":"348"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"349.8",
                    "y":"341"
                },
                "name":"mac"
            },
            {
                "jdipNS:UNIT":{
                    "x":"70.4",
                    "y":"328"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"77.4",
                    "y":"321"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"87.1",
                    "y":"327.7"
                },
                "name":"mad"
            },
            {
                "jdipNS:UNIT":{
                    "x":"267.1",
                    "y":"450"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"274.1",
                    "y":"443"
                },
                "name":"mal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"180.7",
                    "y":"306.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"187.7",
                    "y":"299.4"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"193",
                    "y":"287"
                },
                "name":"mar"
            },
            {
                "jdipNS:UNIT":{
                    "x":"25.2",
                    "y":"221.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"32.2",
                    "y":"214.8"
                },
                "name":"mid"
            },
            {
                "jdipNS:UNIT":{
                    "x":"238.5",
                    "y":"293.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"245.5",
                    "y":"286.8"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"238.1",
                    "y":"308.8"
                },
                "name":"mil"
            },
            {
                "jdipNS:UNIT":{
                    "x":"400.6",
                    "y":"270.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"407.6",
                    "y":"263.2"
                },
                "name":"mol"
            },
            {
                "jdipNS:UNIT":{
                    "x":"198.6",
                    "y":"307.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"205.6",
                    "y":"300.7"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"205",
                    "y":"298"
                },
                "name":"mon"
            },
            {
                "jdipNS:UNIT":{
                    "x":"56.8",
                    "y":"421.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"63.8",
                    "y":"414.6"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"34",
                    "y":"416.8"
                },
                "name":"mor"
            },
            {
                "jdipNS:UNIT":{
                    "x":"446.3",
                    "y":"161"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"453.3",
                    "y":"154"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"475",
                    "y":"160"
                },
                "name":"mos"
            },
            {
                "jdipNS:UNIT":{
                    "x":"236",
                    "y":"258"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"243",
                    "y":"251"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"255.2",
                    "y":"267.6"
                },
                "name":"mun"
            },
            {
                "jdipNS:UNIT":{
                    "x":"471",
                    "y":"57.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"478",
                    "y":"50.8"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"393.3",
                    "y":"24.2"
                },
                "name":"mur"
            },
            {
                "jdipNS:UNIT":{
                    "x":"281.6",
                    "y":"375.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"288.6",
                    "y":"368.4"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"273.5",
                    "y":"364.8"
                },
                "name":"nap"
            },
            {
                "jdipNS:UNIT":{
                    "x":"111.4",
                    "y":"308.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"118.4",
                    "y":"301.1"
                },
                "name":"nav"
            },
            {
                "jdipNS:UNIT":{
                    "x":"64.1",
                    "y":"117.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"71.1",
                    "y":"110.8"
                },
                "name":"nao"
            },
            {
                "jdipNS:UNIT":{
                    "x":"198",
                    "y":"137.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"205",
                    "y":"130.8"
                },
                "name":"nth"
            },
            {
                "jdipNS:UNIT":{
                    "x":"243.8",
                    "y":"111.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"250.8",
                    "y":"104.2"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"262.3",
                    "y":"109"
                },
                "name":"nwy"
            },
            {
                "jdipNS:UNIT":{
                    "x":"200",
                    "y":"84.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"207",
                    "y":"77.7"
                },
                "name":"nwg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"416.4",
                    "y":"249.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"423.4",
                    "y":"242.2"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"430.1",
                    "y":"276"
                },
                "name":"ode"
            },
            {
                "jdipNS:UNIT":{
                    "x":"160.9",
                    "y":"263.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"167.9",
                    "y":"256.9"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"169.1",
                    "y":"243.5"
                },
                "name":"par"
            },
            {
                "jdipNS:UNIT":{
                    "x":"673.9",
                    "y":"473.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"680.9",
                    "y":"466.1"
                },
                "name":"per"
            },
            {
                "jdipNS:UNIT":{
                    "x":"170.8",
                    "y":"222.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"177.8",
                    "y":"215.8"
                },
                "name":"pic"
            },
            {
                "jdipNS:UNIT":{
                    "x":"216.6",
                    "y":"293.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"223.6",
                    "y":"286.1"
                },
                "name":"pie"
            },
            {
                "jdipNS:UNIT":{
                    "x":"381.7",
                    "y":"232.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"388.7",
                    "y":"225.4"
                },
                "name":"pod"
            },
            {
                "jdipNS:UNIT":{
                    "x":"40",
                    "y":"345.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"47",
                    "y":"338.9"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"34.7",
                    "y":"332.6"
                },
                "name":"por"
            },
            {
                "jdipNS:UNIT":{
                    "x":"310.2",
                    "y":"185.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"317.2",
                    "y":"178.6"
                },
                "name":"pru"
            },
            {
                "jdipNS:UNIT":{
                    "x":"534.1",
                    "y":"531"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"541.1",
                    "y":"524"
                },
                "name":"red"
            },
            {
                "jdipNS:UNIT":{
                    "x":"256.4",
                    "y":"343.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"263.4",
                    "y":"336.6"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"251.1",
                    "y":"344.2"
                },
                "name":"rom"
            },
            {
                "jdipNS:UNIT":{
                    "x":"504.7",
                    "y":"272.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"511.7",
                    "y":"265.3"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"522",
                    "y":"273"
                },
                "name":"ros"
            },
            {
                "jdipNS:UNIT":{
                    "x":"217.9",
                    "y":"220.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"224.9",
                    "y":"213.1"
                },
                "name":"ruh"
            },
            {
                "jdipNS:UNIT":{
                    "x":"370.6",
                    "y":"285.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"377.6",
                    "y":"278.8"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"391.2",
                    "y":"311.4"
                },
                "name":"rum"
            },
            {
                "jdipNS:UNIT":{
                    "x":"581.4",
                    "y":"515.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"588.4",
                    "y":"508.2"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"607.7",
                    "y":"492.5"
                },
                "name":"sau"
            },
            {
                "jdipNS:UNIT":{
                    "x":"253.1",
                    "y":"242.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"260.1",
                    "y":"235.7"
                },
                "name":"sax"
            },
            {
                "jdipNS:UNIT":{
                    "x":"338",
                    "y":"325"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"345",
                    "y":"318"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"331.1",
                    "y":"309.3"
                },
                "name":"ser"
            },
            {
                "jdipNS:UNIT":{
                    "x":"455.3",
                    "y":"280.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"462.3",
                    "y":"273.7"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"458.4",
                    "y":"300.8"
                },
                "name":"sev"
            },
            {
                "jdipNS:UNIT":{
                    "x":"62",
                    "y":"349"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"69",
                    "y":"342"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"49.6",
                    "y":"363.8"
                },
                "name":"sve"
            },
            {
                "jdipNS:UNIT":{
                    "x":"646.6",
                    "y":"97.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"653.6",
                    "y":"90.8"
                },
                "name":"sib"
            },
            {
                "jdipNS:UNIT":{
                    "x":"305",
                    "y":"224"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"312",
                    "y":"217"
                },
                "name":"sil"
            },
            {
                "jdipNS:UNIT":{
                    "x":"497.3",
                    "y":"471"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"504.3",
                    "y":"464"
                },
                "name":"sin"
            },
            {
                "jdipNS:UNIT":{
                    "x":"260.4",
                    "y":"129.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"267.4",
                    "y":"122.8"
                },
                "name":"ska"
            },
            {
                "jdipNS:UNIT":{
                    "x":"328.8",
                    "y":"257.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"335.8",
                    "y":"250.9"
                },
                "name":"slk"
            },
            {
                "jdipNS:UNIT":{
                    "x":"15.8",
                    "y":"399.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"22.8",
                    "y":"392.5"
                },
                "name":"sao"
            },
            {
                "jdipNS:UNIT":{
                    "x":"401.6",
                    "y":"120.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"408.6",
                    "y":"113.9"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"397.6",
                    "y":"107.7"
                },
                "name":"stp"
            },
            {
                "jdipNS:UNIT":{
                    "x":"70",
                    "y":"391"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"77",
                    "y":"384"
                },
                "name":"sog"
            },
            {
                "jdipNS:UNIT":{
                    "x":"288.1",
                    "y":"134.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"295.1",
                    "y":"127.6"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"309.4",
                    "y":"124.3"
                },
                "name":"swe"
            },
            {
                "jdipNS:UNIT":{
                    "x":"218",
                    "y":"278"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"225",
                    "y":"271"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"225",
                    "y":"271"
                },
                "name":"swi"
            },
            {
                "jdipNS:UNIT":{
                    "x":"545.7",
                    "y":"395.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"552.7",
                    "y":"388.3"
                },
                "name":"syr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"215.5",
                    "y":"456.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"222.5",
                    "y":"449.3"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"215.8",
                    "y":"429.5"
                },
                "name":"tun"
            },
            {
                "jdipNS:UNIT":{
                    "x":"237.1",
                    "y":"321.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"244.1",
                    "y":"314.7"
                },
                "name":"tus"
            },
            {
                "jdipNS:UNIT":{
                    "x":"239.7",
                    "y":"362.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"246.7",
                    "y":"355.7"
                },
                "name":"tyr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"538.3",
                    "y":"26.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"545.3",
                    "y":"19.3"
                },
                "name":"ura"
            },
            {
                "jdipNS:UNIT":{
                    "x":"255.1",
                    "y":"317.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"262.1",
                    "y":"310.7"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"261.7",
                    "y":"295.3"
                },
                "name":"ven"
            },
            {
                "jdipNS:UNIT":{
                    "x":"525.7",
                    "y":"202.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"532.7",
                    "y":"195.9"
                },
                "name":"vol"
            },
            {
                "jdipNS:UNIT":{
                    "x":"141.5",
                    "y":"198.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"148.5",
                    "y":"191.9"
                },
                "name":"wal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"320.1",
                    "y":"203.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"327.1",
                    "y":"196.5"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"335.3",
                    "y":"214.5"
                },
                "name":"war"
            },
            {
                "jdipNS:UNIT":{
                    "x":"431.1",
                    "y":"339.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"438.1",
                    "y":"332.6"
                },
                "name":"wbs"
            },
            {
                "jdipNS:UNIT":{
                    "x":"132.5",
                    "y":"390.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"139.5",
                    "y":"383.1"
                },
                "name":"wme"
            },
            {
                "jdipNS:UNIT":{
                    "x":"58.9",
                    "y":"521.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"65.9",
                    "y":"514.5"
                },
                "name":"wsa"
            },
            {
                "jdipNS:UNIT":{
                    "x":"434.2",
                    "y":"17.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"441.2",
                    "y":"10.9"
                },
                "name":"whi"
            },
            {
                "jdipNS:UNIT":{
                    "x":"166.1",
                    "y":"163.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"173.1",
                    "y":"156.7"
                },
                "name":"yor"
            }
        ],
        "dislodgedUnitOffset":"7,-7"
    }
};
            