/**
==============================================================================
Copyright (C) 2019 - Philip Paquette, Steven Bocco

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License along
 with this program.  If not, see <https:www.gnu.org/licenses/>.
==============================================================================
**/
export const SvgModernExtra = {
    "jdipNS:DISPLAY":{
        "jdipNS:ZOOM":{
            "min":"5",
            "max":"2200",
            "factor":"1.2"
        },
        "jdipNS:LABELS":{
            "brief":"true",
            "full":"false"
        }
    },
    "jdipNS:ORDERDRAWING":{
        "jdipNS:POWERCOLORS":{
            "jdipNS:POWERCOLOR":[
                {
                    "power":"Britain",
                    "color":"royalblue"
                },
                {
                    "power":"Egypt",
                    "color":"#808000"
                },
                {
                    "power":"France",
                    "color":"#00FFFF"
                },
                {
                    "power":"Germany",
                    "color":"darkgrey"
                },
                {
                    "power":"Italy",
                    "color":"#80FF80"
                },
                {
                    "power":"Poland",
                    "color":"#FF0000"
                },
                {
                    "power":"Russia",
                    "color":"#008000"
                },
                {
                    "power":"Spain",
                    "color":"#FF8080"
                },
                {
                    "power":"Turkey",
                    "color":"#FFFF00"
                },
                {
                    "power":"Ukraine",
                    "color":"#FF00FF"
                }
            ]
        },
        "jdipNS:SYMBOLSIZE":[
            {
                "name":"Fleet",
                "width":"16",
                "height":"16"
            },
            {
                "name":"Army",
                "width":"16",
                "height":"16"
            },
            {
                "name":"Wing",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedFleet",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedArmy",
                "width":"20",
                "height":"20"
            },
            {
                "name":"DislodgedWing",
                "width":"20",
                "height":"20"
            },
            {
                "name":"FailedOrder",
                "width":"17",
                "height":"17"
            },
            {
                "name":"SupplyCenter",
                "width":"5",
                "height":"5"
            },
            {
                "name":"BuildUnit",
                "width":"24",
                "height":"24"
            },
            {
                "name":"RemoveUnit",
                "width":"24",
                "height":"24"
            },
            {
                "name":"WaivedBuild",
                "width":"25",
                "height":"25"
            },
            {
                "name":"HoldUnit",
                "width":"30",
                "height":"30"
            },
            {
                "name":"SupportHoldUnit",
                "width":"34.5",
                "height":"34.5"
            },
            {
                "name":"ConvoyTriangle",
                "width":"40",
                "height":"34.5"
            },
            {
                "name":"Stroke",
                "width":"2",
                "height":"4"
            }
        ]
    },
    "jdipNS:PROVINCE_DATA":{
        "jdipNS:PROVINCE":[
            {
                "jdipNS:UNIT":{
                    "x":"527.9",
                    "y":"356.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"531.9",
                    "y":"352.9"
                },
                "name":"ada"
            },
            {
                "jdipNS:UNIT":{
                    "x":"83.099998",
                    "y":"359.79999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"87.099998",
                    "y":"355.79999"
                },
                "name":"adl"
            },
            {
                "jdipNS:UNIT":{
                    "x":"276.8",
                    "y":"332.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"280.8",
                    "y":"328.9"
                },
                "name":"adr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"371.2",
                    "y":"385.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"375.2",
                    "y":"381.3"
                },
                "name":"aeg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"314.4",
                    "y":"350.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"318.4",
                    "y":"346.6"
                },
                "name":"alb"
            },
            {
                "jdipNS:UNIT":{
                    "x":"404.7779804",
                    "y":"502.3397129"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"408.7779804",
                    "y":"498.3397129"
                },
                "name":"ale"
            },
            {
                "jdipNS:UNIT":{
                    "x":"130.4",
                    "y":"444.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"134.4",
                    "y":"440.2"
                },
                "name":"alg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"187.8",
                    "y":"238.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"191.8",
                    "y":"234.0"
                },
                "name":"als"
            },
            {
                "jdipNS:UNIT":{
                    "x":"455.3",
                    "y":"379.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"459.3",
                    "y":"375.0"
                },
                "name":"ana"
            },
            {
                "jdipNS:UNIT":{
                    "x":"455.3",
                    "y":"339.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"459.3",
                    "y":"335.1"
                },
                "name":"ank"
            },
            {
                "jdipNS:UNIT":{
                    "x":"269.5",
                    "y":"345.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"273.5",
                    "y":"341.5"
                },
                "name":"apu"
            },
            {
                "jdipNS:UNIT":{
                    "x":"674.0",
                    "y":"520.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"678.0",
                    "y":"516.6"
                },
                "name":"ara"
            },
            {
                "jdipNS:UNIT":{
                    "x":"196.3",
                    "y":"5.800000000000001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"200.3",
                    "y":"1.8000000000000007"
                },
                "name":"arc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"562.40002",
                    "y":"322.89999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"566.40002",
                    "y":"318.89999"
                },
                "name":"arm"
            },
            {
                "jdipNS:UNIT":{
                    "x":"446.219627",
                    "y":"539.3794358"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"450.219627",
                    "y":"535.3794358"
                },
                "name":"asw"
            },
            {
                "jdipNS:UNIT":{
                    "x":"268.89999",
                    "y":"268.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"272.89999",
                    "y":"264.5"
                },
                "name":"aus"
            },
            {
                "jdipNS:UNIT":{
                    "x":"146.39999",
                    "y":"300.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"150.39999",
                    "y":"296.5"
                },
                "name":"auv"
            },
            {
                "jdipNS:UNIT":{
                    "x":"591.59998",
                    "y":"312.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"595.59998",
                    "y":"308.5"
                },
                "name":"aze"
            },
            {
                "jdipNS:UNIT":{
                    "x":"310.0",
                    "y":"136.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"314.0",
                    "y":"132.4"
                },
                "name":"bal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"113.6",
                    "y":"322.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"117.6",
                    "y":"318.2"
                },
                "name":"bar"
            },
            {
                "jdipNS:UNIT":{
                    "x":"177.8",
                    "y":"206.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"181.8",
                    "y":"202.8"
                },
                "name":"bel"
            },
            {
                "jdipNS:UNIT":{
                    "x":"260.79999",
                    "y":"188.89999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"264.79999",
                    "y":"184.89999"
                },
                "name":"ber"
            },
            {
                "jdipNS:UNIT":{
                    "x":"264.1",
                    "y":"165.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"268.1",
                    "y":"161.6"
                },
                "name":"bhm"
            },
            {
                "jdipNS:UNIT":{
                    "x":"366.0",
                    "y":"189.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"370.0",
                    "y":"185.8"
                },
                "name":"bie"
            },
            {
                "jdipNS:UNIT":{
                    "x":"86.2",
                    "y":"239.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"90.2",
                    "y":"235.3"
                },
                "name":"bis"
            },
            {
                "jdipNS:UNIT":{
                    "x":"133.6",
                    "y":"278.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"137.6",
                    "y":"274.1"
                },
                "name":"bor"
            },
            {
                "jdipNS:UNIT":{
                    "x":"294.7",
                    "y":"307.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"298.7",
                    "y":"303.0"
                },
                "name":"bos"
            },
            {
                "jdipNS:UNIT":{
                    "x":"126.19999999999999",
                    "y":"232.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"130.2",
                    "y":"228.9"
                },
                "name":"bri"
            },
            {
                "jdipNS:UNIT":{
                    "x":"287.10001",
                    "y":"4.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"291.10001",
                    "y":"0.40000000000000036"
                },
                "name":"brn"
            },
            {
                "jdipNS:UNIT":{
                    "x":"380.70001",
                    "y":"328.20001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"384.70001",
                    "y":"324.20001"
                },
                "name":"bul"
            },
            {
                "jdipNS:UNIT":{
                    "x":"475.3",
                    "y":"503.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"479.3",
                    "y":"499.1"
                },
                "name":"cai"
            },
            {
                "jdipNS:UNIT":{
                    "x":"626.7",
                    "y":"311.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"630.7",
                    "y":"307.7"
                },
                "name":"cas"
            },
            {
                "jdipNS:UNIT":{
                    "x":"552.90002",
                    "y":"273.70001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"556.90002",
                    "y":"269.70001"
                },
                "name":"cau"
            },
            {
                "jdipNS:UNIT":{
                    "x":"144.0",
                    "y":"94.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"148.0",
                    "y":"90.6"
                },
                "name":"cly"
            },
            {
                "jdipNS:UNIT":{
                    "x":"280.70001",
                    "y":"287.10001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"284.70001",
                    "y":"283.10001"
                },
                "name":"cro"
            },
            {
                "jdipNS:UNIT":{
                    "x":"434.3",
                    "y":"183.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"438.3",
                    "y":"179.5"
                },
                "name":"crp"
            },
            {
                "jdipNS:UNIT":{
                    "x":"277.5",
                    "y":"240.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"281.5",
                    "y":"236.0"
                },
                "name":"cze"
            },
            {
                "jdipNS:UNIT":{
                    "x":"242.2",
                    "y":"147.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"246.2",
                    "y":"143.7"
                },
                "name":"den"
            },
            {
                "jdipNS:UNIT":{
                    "x":"476.29999",
                    "y":"245.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"480.29999",
                    "y":"241.3"
                },
                "name":"don"
            },
            {
                "jdipNS:UNIT":{
                    "x":"475.20001",
                    "y":"306.89999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"479.20001",
                    "y":"302.89999"
                },
                "name":"ebs"
            },
            {
                "jdipNS:UNIT":{
                    "x":"159.8631679",
                    "y":"111.8947368"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"163.8631679",
                    "y":"107.8947368"
                },
                "name":"edi"
            },
            {
                "jdipNS:UNIT":{
                    "x":"412.301904",
                    "y":"434.5191388"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"416.301904",
                    "y":"430.5191388"
                },
                "name":"eme"
            },
            {
                "jdipNS:UNIT":{
                    "x":"71.6",
                    "y":"206.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"75.6",
                    "y":"202.8"
                },
                "name":"eng"
            },
            {
                "jdipNS:UNIT":{
                    "x":"355.4",
                    "y":"475.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"359.4",
                    "y":"471.7"
                },
                "name":"esa"
            },
            {
                "jdipNS:UNIT":{
                    "x":"359.7",
                    "y":"111.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"363.7",
                    "y":"107.2"
                },
                "name":"est"
            },
            {
                "jdipNS:UNIT":{
                    "x":"356.5",
                    "y":"62.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"360.5",
                    "y":"58.5"
                },
                "name":"fin"
            },
            {
                "jdipNS:UNIT":{
                    "x":"233.60001",
                    "y":"212.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"237.60001",
                    "y":"208.8"
                },
                "name":"fra"
            },
            {
                "jdipNS:UNIT":{
                    "x":"325.89999",
                    "y":"173.60001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"329.89999",
                    "y":"169.60001"
                },
                "name":"gda"
            },
            {
                "jdipNS:UNIT":{
                    "x":"534.20001",
                    "y":"302.10001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"538.20001",
                    "y":"298.10001"
                },
                "name":"geo"
            },
            {
                "jdipNS:UNIT":{
                    "x":"50.5",
                    "y":"366.10001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"54.5",
                    "y":"362.10001"
                },
                "name":"gib"
            },
            {
                "jdipNS:UNIT":{
                    "x":"316.6",
                    "y":"97.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"320.6",
                    "y":"93.9"
                },
                "name":"gob"
            },
            {
                "jdipNS:UNIT":{
                    "x":"135.7",
                    "y":"346.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"139.7",
                    "y":"342.4"
                },
                "name":"gol"
            },
            {
                "jdipNS:UNIT":{
                    "x":"522.6",
                    "y":"93.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"526.6",
                    "y":"89.0"
                },
                "name":"gor"
            },
            {
                "jdipNS:UNIT":{
                    "x":"335.5",
                    "y":"367.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"339.5",
                    "y":"363.5"
                },
                "name":"gre"
            },
            {
                "jdipNS:UNIT":{
                    "x":"227.60001",
                    "y":"190.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"231.60001",
                    "y":"186.2"
                },
                "name":"ham"
            },
            {
                "jdipNS:UNIT":{
                    "x":"214.3",
                    "y":"163.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"218.3",
                    "y":"159.0"
                },
                "name":"hel"
            },
            {
                "jdipNS:UNIT":{
                    "x":"196.39999",
                    "y":"188.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"200.39999",
                    "y":"184.2"
                },
                "name":"hol"
            },
            {
                "jdipNS:UNIT":{
                    "x":"309.29999",
                    "y":"275.20001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"313.29999",
                    "y":"271.20001"
                },
                "name":"hun"
            },
            {
                "jdipNS:UNIT":{
                    "x":"113.6",
                    "y":"22.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"117.6",
                    "y":"18.6"
                },
                "name":"ice"
            },
            {
                "jdipNS:UNIT":{
                    "x":"302.9",
                    "y":"391.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"306.9",
                    "y":"387.6"
                },
                "name":"ion"
            },
            {
                "jdipNS:UNIT":{
                    "x":"96.2",
                    "y":"139.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"100.2",
                    "y":"135.8"
                },
                "name":"ire"
            },
            {
                "jdipNS:UNIT":{
                    "x":"96.8",
                    "y":"172.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"100.8",
                    "y":"168.3"
                },
                "name":"iri"
            },
            {
                "jdipNS:UNIT":{
                    "x":"569.9",
                    "y":"387.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"573.9",
                    "y":"383.4"
                },
                "name":"irk"
            },
            {
                "jdipNS:UNIT":{
                    "x":"624.6",
                    "y":"385.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"628.6",
                    "y":"381.3"
                },
                "name":"irn"
            },
            {
                "jdipNS:UNIT":{
                    "x":"639.2",
                    "y":"357.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"643.2",
                    "y":"353.5"
                },
                "name":"irn-nc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"679.2",
                    "y":"446.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"683.2",
                    "y":"442.8"
                },
                "name":"irn-sc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"494.20001",
                    "y":"424.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"498.20001",
                    "y":"420.0"
                },
                "name":"isr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"422.7",
                    "y":"355.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"426.7",
                    "y":"351.9"
                },
                "name":"ist"
            },
            {
                "jdipNS:UNIT":{
                    "x":"398.5",
                    "y":"381.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"402.5",
                    "y":"377.1"
                },
                "name":"izm"
            },
            {
                "jdipNS:UNIT":{
                    "x":"512.0999800861243",
                    "y":"453.306689"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"516.0999800861243",
                    "y":"449.306689"
                },
                "name":"jor"
            },
            {
                "jdipNS:UNIT":{
                    "x":"644.6",
                    "y":"198.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"648.6",
                    "y":"194.2"
                },
                "name":"kaz"
            },
            {
                "jdipNS:UNIT":{
                    "x":"478.5",
                    "y":"224.39999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"482.5",
                    "y":"220.39999"
                },
                "name":"kha"
            },
            {
                "jdipNS:UNIT":{
                    "x":"428.0",
                    "y":"214.60001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"432.0",
                    "y":"210.60001"
                },
                "name":"kie"
            },
            {
                "jdipNS:UNIT":{
                    "x":"334.4",
                    "y":"221.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"338.4",
                    "y":"217.3"
                },
                "name":"kra"
            },
            {
                "jdipNS:UNIT":{
                    "x":"332.29999",
                    "y":"7.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"336.29999",
                    "y":"3.0999999999999996"
                },
                "name":"lap"
            },
            {
                "jdipNS:UNIT":{
                    "x":"361.20001",
                    "y":"137.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"365.20001",
                    "y":"133.7"
                },
                "name":"lat"
            },
            {
                "jdipNS:UNIT":{
                    "x":"306.525847",
                    "y":"450.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"310.525847",
                    "y":"446.5"
                },
                "name":"lbn"
            },
            {
                "jdipNS:UNIT":{
                    "x":"301.8",
                    "y":"501.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"305.8",
                    "y":"497.0"
                },
                "name":"lib"
            },
            {
                "jdipNS:UNIT":{
                    "x":"194.5",
                    "y":"323.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"198.5",
                    "y":"319.0"
                },
                "name":"lig"
            },
            {
                "jdipNS:UNIT":{
                    "x":"347.10001",
                    "y":"161.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"351.10001",
                    "y":"157.0"
                },
                "name":"lit"
            },
            {
                "jdipNS:UNIT":{
                    "x":"134.7",
                    "y":"137.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"138.7",
                    "y":"133.8"
                },
                "name":"liv"
            },
            {
                "jdipNS:UNIT":{
                    "x":"160.60001",
                    "y":"182.89999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"164.60001",
                    "y":"178.89999"
                },
                "name":"lon"
            },
            {
                "jdipNS:UNIT":{
                    "x":"164.5",
                    "y":"264.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"168.5",
                    "y":"260.0"
                },
                "name":"lyo"
            },
            {
                "jdipNS:UNIT":{
                    "x":"335.29999",
                    "y":"344.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"339.29999",
                    "y":"340.0"
                },
                "name":"mac"
            },
            {
                "jdipNS:UNIT":{
                    "x":"66.900002",
                    "y":"318.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"70.900002",
                    "y":"314.0"
                },
                "name":"mad"
            },
            {
                "jdipNS:UNIT":{
                    "x":"255.60000000000002",
                    "y":"440.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"259.6",
                    "y":"436.0"
                },
                "name":"mal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"171.2",
                    "y":"292.39999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"175.2",
                    "y":"288.39999"
                },
                "name":"mar"
            },
            {
                "jdipNS:UNIT":{
                    "x":"13.7",
                    "y":"211.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"17.7",
                    "y":"207.8"
                },
                "name":"mid"
            },
            {
                "jdipNS:UNIT":{
                    "x":"227.0",
                    "y":"283.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"231.0",
                    "y":"279.8"
                },
                "name":"mil"
            },
            {
                "jdipNS:UNIT":{
                    "x":"391.10001",
                    "y":"262.20001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"395.10001",
                    "y":"258.20001"
                },
                "name":"mol"
            },
            {
                "jdipNS:UNIT":{
                    "x":"187.10001",
                    "y":"301.70001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"191.10001",
                    "y":"297.70001"
                },
                "name":"mon"
            },
            {
                "jdipNS:UNIT":{
                    "x":"45.3",
                    "y":"411.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"49.3",
                    "y":"407.6"
                },
                "name":"mor"
            },
            {
                "jdipNS:UNIT":{
                    "x":"434.8",
                    "y":"151.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"438.8",
                    "y":"147.0"
                },
                "name":"mos"
            },
            {
                "jdipNS:UNIT":{
                    "x":"224.5",
                    "y":"248.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"228.5",
                    "y":"244.0"
                },
                "name":"mun"
            },
            {
                "jdipNS:UNIT":{
                    "x":"451.5",
                    "y":"51.799999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"455.5",
                    "y":"47.799999"
                },
                "name":"mur"
            },
            {
                "jdipNS:UNIT":{
                    "x":"52.599999999999994",
                    "y":"107.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"56.599999999999994",
                    "y":"103.8"
                },
                "name":"nao"
            },
            {
                "jdipNS:UNIT":{
                    "x":"270.1",
                    "y":"365.4"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"274.1",
                    "y":"361.4"
                },
                "name":"nap"
            },
            {
                "jdipNS:UNIT":{
                    "x":"99.9",
                    "y":"298.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"103.9",
                    "y":"294.1"
                },
                "name":"nav"
            },
            {
                "jdipNS:UNIT":{
                    "x":"186.5",
                    "y":"127.80000000000001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"190.5",
                    "y":"123.80000000000001"
                },
                "name":"nth"
            },
            {
                "jdipNS:UNIT":{
                    "x":"188.5",
                    "y":"74.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"192.5",
                    "y":"70.7"
                },
                "name":"nwg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"232.3",
                    "y":"101.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"236.3",
                    "y":"97.2"
                },
                "name":"nwy"
            },
            {
                "jdipNS:UNIT":{
                    "x":"406.89999",
                    "y":"241.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"410.89999",
                    "y":"237.2"
                },
                "name":"ode"
            },
            {
                "jdipNS:UNIT":{
                    "x":"149.39999",
                    "y":"243.89999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"153.39999",
                    "y":"239.89999"
                },
                "name":"par"
            },
            {
                "jdipNS:UNIT":{
                    "x":"662.4",
                    "y":"463.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"666.4",
                    "y":"459.1"
                },
                "name":"per"
            },
            {
                "jdipNS:UNIT":{
                    "x":"159.3",
                    "y":"220.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"163.3",
                    "y":"216.8"
                },
                "name":"pic"
            },
            {
                "jdipNS:UNIT":{
                    "x":"205.10001",
                    "y":"291.10001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"209.10001",
                    "y":"287.10001"
                },
                "name":"pie"
            },
            {
                "jdipNS:UNIT":{
                    "x":"370.20001",
                    "y":"232.39999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"374.20001",
                    "y":"228.39999"
                },
                "name":"pod"
            },
            {
                "jdipNS:UNIT":{
                    "x":"30.5",
                    "y":"315.89999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"34.5",
                    "y":"311.89999"
                },
                "name":"por"
            },
            {
                "jdipNS:UNIT":{
                    "x":"294.70001",
                    "y":"181.60001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"298.70001",
                    "y":"177.60001"
                },
                "name":"pru"
            },
            {
                "jdipNS:UNIT":{
                    "x":"522.6",
                    "y":"521.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"526.6",
                    "y":"517.0"
                },
                "name":"red"
            },
            {
                "jdipNS:UNIT":{
                    "x":"244.89999999999998",
                    "y":"333.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"248.89999999999998",
                    "y":"329.6"
                },
                "name":"rom"
            },
            {
                "jdipNS:UNIT":{
                    "x":"493.20001",
                    "y":"270.29999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"497.20001",
                    "y":"266.29999"
                },
                "name":"ros"
            },
            {
                "jdipNS:UNIT":{
                    "x":"206.4",
                    "y":"210.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"210.4",
                    "y":"206.1"
                },
                "name":"ruh"
            },
            {
                "jdipNS:UNIT":{
                    "x":"359.10001",
                    "y":"285.79999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"363.10001",
                    "y":"281.79999"
                },
                "name":"rum"
            },
            {
                "jdipNS:UNIT":{
                    "x":"4.300000000000001",
                    "y":"389.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"8.3",
                    "y":"385.5"
                },
                "name":"sao"
            },
            {
                "jdipNS:UNIT":{
                    "x":"569.9",
                    "y":"505.20000000000005"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"573.9",
                    "y":"501.20000000000005"
                },
                "name":"sau"
            },
            {
                "jdipNS:UNIT":{
                    "x":"245.60001",
                    "y":"232.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"249.60001",
                    "y":"228.7"
                },
                "name":"sax"
            },
            {
                "jdipNS:UNIT":{
                    "x":"326.5",
                    "y":"315.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"330.5",
                    "y":"311.0"
                },
                "name":"ser"
            },
            {
                "jdipNS:UNIT":{
                    "x":"443.8",
                    "y":"270.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"447.8",
                    "y":"266.7"
                },
                "name":"sev"
            },
            {
                "jdipNS:UNIT":{
                    "x":"635.1",
                    "y":"87.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"639.1",
                    "y":"83.8"
                },
                "name":"sib"
            },
            {
                "jdipNS:UNIT":{
                    "x":"293.5",
                    "y":"214.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"297.5",
                    "y":"210.0"
                },
                "name":"sil"
            },
            {
                "jdipNS:UNIT":{
                    "x":"485.13013354",
                    "y":"468.3684211"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"489.13013354",
                    "y":"464.3684211"
                },
                "name":"sin"
            },
            {
                "jdipNS:UNIT":{
                    "x":"248.89999999999998",
                    "y":"119.80000000000001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"252.89999999999998",
                    "y":"115.80000000000001"
                },
                "name":"ska"
            },
            {
                "jdipNS:UNIT":{
                    "x":"313.29999",
                    "y":"251.89999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"317.29999",
                    "y":"247.89999"
                },
                "name":"slk"
            },
            {
                "jdipNS:UNIT":{
                    "x":"64.5",
                    "y":"387.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"68.5",
                    "y":"383.0"
                },
                "name":"sog"
            },
            {
                "jdipNS:UNIT":{
                    "x":"390.1",
                    "y":"110.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"394.1",
                    "y":"106.9"
                },
                "name":"stp"
            },
            {
                "jdipNS:UNIT":{
                    "x":"50.5",
                    "y":"339.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"54.5",
                    "y":"335.0"
                },
                "name":"sve"
            },
            {
                "jdipNS:UNIT":{
                    "x":"276.6",
                    "y":"124.6"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"280.6",
                    "y":"120.6"
                },
                "name":"swe"
            },
            {
                "jdipNS:UNIT":{
                    "x":"206.5",
                    "y":"268.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"210.5",
                    "y":"264.0"
                },
                "name":"swi"
            },
            {
                "jdipNS:UNIT":{
                    "x":"528.20001",
                    "y":"395.29999"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"532.20001",
                    "y":"391.29999"
                },
                "name":"syr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"204.0",
                    "y":"446.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"208.0",
                    "y":"442.3"
                },
                "name":"tun"
            },
            {
                "jdipNS:UNIT":{
                    "x":"225.6",
                    "y":"311.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"229.6",
                    "y":"307.7"
                },
                "name":"tus"
            },
            {
                "jdipNS:UNIT":{
                    "x":"234.2",
                    "y":"374.70001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"238.2",
                    "y":"370.70001"
                },
                "name":"tyr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"526.8",
                    "y":"16.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"530.8",
                    "y":"12.3"
                },
                "name":"ura"
            },
            {
                "jdipNS:UNIT":{
                    "x":"249.60001",
                    "y":"309.70001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"253.60001",
                    "y":"305.70001"
                },
                "name":"ven"
            },
            {
                "jdipNS:UNIT":{
                    "x":"514.2",
                    "y":"192.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"518.2",
                    "y":"188.9"
                },
                "name":"vol"
            },
            {
                "jdipNS:UNIT":{
                    "x":"130.0",
                    "y":"188.9"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"134.0",
                    "y":"184.9"
                },
                "name":"wal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"316.60001",
                    "y":"203.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"320.60001",
                    "y":"199.5"
                },
                "name":"war"
            },
            {
                "jdipNS:UNIT":{
                    "x":"423.60001",
                    "y":"309.60001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"427.60001",
                    "y":"305.60001"
                },
                "name":"wbs"
            },
            {
                "jdipNS:UNIT":{
                    "x":"422.70001",
                    "y":"9.9000001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"426.70001",
                    "y":"5.9000001"
                },
                "name":"whi"
            },
            {
                "jdipNS:UNIT":{
                    "x":"143.0",
                    "y":"380.10001"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"147.0",
                    "y":"376.10001"
                },
                "name":"wme"
            },
            {
                "jdipNS:UNIT":{
                    "x":"47.4",
                    "y":"511.5"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"51.4",
                    "y":"507.5"
                },
                "name":"wsa"
            },
            {
                "jdipNS:UNIT":{
                    "x":"154.6",
                    "y":"153.7"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"158.6",
                    "y":"149.7"
                },
                "name":"yor"
            }
        ]
    }
};
            