/**
==============================================================================
Copyright (C) 2019 - Philip Paquette, Steven Bocco

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License along
 with this program.  If not, see <https:www.gnu.org/licenses/>.
==============================================================================
**/
export const SvgStandardExtra = {
    "jdipNS:DISPLAY":{
        "jdipNS:ZOOM":{
            "min":"5",
            "max":"2200",
            "factor":"1.2"
        },
        "jdipNS:LABELS":{
            "brief":"true",
            "full":"true"
        }
    },
    "jdipNS:ORDERDRAWING":{
        "jdipNS:POWERCOLORS":{
            "jdipNS:POWERCOLOR":[
                {
                    "power":"austria",
                    "color":"#c48f85"
                },
                {
                    "power":"england",
                    "color":"darkviolet"
                },
                {
                    "power":"france",
                    "color":"royalblue"
                },
                {
                    "power":"germany",
                    "color":"#a08a75"
                },
                {
                    "power":"italy",
                    "color":"forestgreen"
                },
                {
                    "power":"russia",
                    "color":"#757d91"
                },
                {
                    "power":"turkey",
                    "color":"#b9a61c"
                }
            ]
        },
        "jdipNS:SYMBOLSIZE":[
            {
                "name":"Fleet",
                "width":"40",
                "height":"40"
            },
            {
                "name":"Army",
                "width":"40",
                "height":"40"
            },
            {
                "name":"Wing",
                "width":"40",
                "height":"40"
            },
            {
                "name":"DislodgedFleet",
                "width":"40",
                "height":"40"
            },
            {
                "name":"DislodgedArmy",
                "width":"40",
                "height":"40"
            },
            {
                "name":"DislodgedWing",
                "width":"40",
                "height":"40"
            },
            {
                "name":"FailedOrder",
                "width":"30",
                "height":"30"
            },
            {
                "name":"SupplyCenter",
                "width":"20",
                "height":"20"
            },
            {
                "name":"BuildUnit",
                "width":"60",
                "height":"60"
            },
            {
                "name":"RemoveUnit",
                "width":"50",
                "height":"50"
            },
            {
                "name":"WaivedBuild",
                "width":"40",
                "height":"40"
            },
            {
                "name":"HoldUnit",
                "width":"66.6",
                "height":"66.6"
            },
            {
                "name":"SupportHoldUnit",
                "width":"76.6",
                "height":"76.6"
            },
            {
                "name":"ConvoyTriangle",
                "width":"66.4",
                "height":"57.4"
            },
            {
                "name":"Stroke",
                "width":"6",
                "height":"10"
            }
        ]
    },
    "jdipNS:PROVINCE_DATA":{
        "jdipNS:PROVINCE":[
            {
                "jdipNS:UNIT":{
                    "x":"793.5",
                    "y":"1048.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"782.0",
                    "y":"1038.0"
                },
                "name":"adr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1043.5",
                    "y":"1230.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1032.0",
                    "y":"1220.0"
                },
                "name":"aeg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"906.5",
                    "y":"1113.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"895.0",
                    "y":"1103.0"
                },
                "name":"alb"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1301.5",
                    "y":"1110.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1290.0",
                    "y":"1100.0"
                },
                "name":"ank"
            },
            {
                "jdipNS:UNIT":{
                    "x":"791.5",
                    "y":"1106.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"780.0",
                    "y":"1096.0"
                },
                "name":"apu"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1484.5",
                    "y":"1090.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1473.0",
                    "y":"1080.0"
                },
                "name":"arm"
            },
            {
                "jdipNS:UNIT":{
                    "x":"878.5",
                    "y":"610.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"867.0",
                    "y":"600.0"
                },
                "name":"bal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1162.5",
                    "y":"73.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1151.0",
                    "y":"63.0"
                },
                "name":"bar"
            },
            {
                "jdipNS:UNIT":{
                    "x":"561.5",
                    "y":"753.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"550.0",
                    "y":"743.0"
                },
                "name":"bel"
            },
            {
                "jdipNS:UNIT":{
                    "x":"771.5",
                    "y":"690.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"760.0",
                    "y":"680.0"
                },
                "name":"ber"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1233.5",
                    "y":"1000.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1222.0",
                    "y":"990.0"
                },
                "name":"bla"
            },
            {
                "jdipNS:UNIT":{
                    "x":"806.5",
                    "y":"814.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"795.0",
                    "y":"804.0"
                },
                "name":"boh"
            },
            {
                "jdipNS:UNIT":{
                    "x":"941.5",
                    "y":"485.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"930.0",
                    "y":"475.0"
                },
                "name":"bot"
            },
            {
                "jdipNS:UNIT":{
                    "x":"404.5",
                    "y":"819.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"393.0",
                    "y":"809.0"
                },
                "name":"bre"
            },
            {
                "jdipNS:UNIT":{
                    "x":"950.5",
                    "y":"904.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"939.0",
                    "y":"894.0"
                },
                "name":"bud"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1048.5",
                    "y":"1068.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1037.0",
                    "y":"1058.0"
                },
                "name":"bul"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1127.0",
                    "y":"1067.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1115.5",
                    "y":"1057.0"
                },
                "name":"bul-ec"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1070.0",
                    "y":"1140.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1058.5",
                    "y":"1130.0"
                },
                "name":"bul-sc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"559.5",
                    "y":"871.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"548.0",
                    "y":"861.0"
                },
                "name":"bur"
            },
            {
                "jdipNS:UNIT":{
                    "x":"436.5",
                    "y":"492.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"425.0",
                    "y":"482.0"
                },
                "name":"cly"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1145.5",
                    "y":"1137.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1134.0",
                    "y":"1127.0"
                },
                "name":"con"
            },
            {
                "jdipNS:UNIT":{
                    "x":"703.5",
                    "y":"587.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"692.0",
                    "y":"577.0"
                },
                "name":"den"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1218.5",
                    "y":"1311.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1207.0",
                    "y":"1301.0"
                },
                "name":"eas"
            },
            {
                "jdipNS:UNIT":{
                    "x":"473.5",
                    "y":"514.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"462.0",
                    "y":"504.0"
                },
                "name":"edi"
            },
            {
                "jdipNS:UNIT":{
                    "x":"394.5",
                    "y":"751.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"383.0",
                    "y":"741.0"
                },
                "name":"eng"
            },
            {
                "jdipNS:UNIT":{
                    "x":"988.5",
                    "y":"380.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"977.0",
                    "y":"370.0"
                },
                "name":"fin"
            },
            {
                "jdipNS:UNIT":{
                    "x":"999.5",
                    "y":"831.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"988.0",
                    "y":"821.0"
                },
                "name":"gal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"422.5",
                    "y":"912.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"411.0",
                    "y":"902.0"
                },
                "name":"gas"
            },
            {
                "jdipNS:UNIT":{
                    "x":"556.0",
                    "y":"1060.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"544.5",
                    "y":"1050.0"
                },
                "name":"gol"
            },
            {
                "jdipNS:UNIT":{
                    "x":"966.5",
                    "y":"1190.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"955.0",
                    "y":"1180.0"
                },
                "name":"gre"
            },
            {
                "jdipNS:UNIT":{
                    "x":"651.5",
                    "y":"631.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"640.0",
                    "y":"621.0"
                },
                "name":"hel"
            },
            {
                "jdipNS:UNIT":{
                    "x":"596.5",
                    "y":"711.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"585.0",
                    "y":"701.0"
                },
                "name":"hol"
            },
            {
                "jdipNS:UNIT":{
                    "x":"846.5",
                    "y":"1286.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"835.0",
                    "y":"1276.0"
                },
                "name":"ion"
            },
            {
                "jdipNS:UNIT":{
                    "x":"335.5",
                    "y":"661.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"324.0",
                    "y":"651.0"
                },
                "name":"iri"
            },
            {
                "jdipNS:UNIT":{
                    "x":"683.5",
                    "y":"701.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"672.0",
                    "y":"691.0"
                },
                "name":"kie"
            },
            {
                "jdipNS:UNIT":{
                    "x":"488.5",
                    "y":"675.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"477.0",
                    "y":"665.0"
                },
                "name":"lon"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1025.5",
                    "y":"567.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1014.0",
                    "y":"557.0"
                },
                "name":"lvn"
            },
            {
                "jdipNS:UNIT":{
                    "x":"450.5",
                    "y":"576.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"439.0",
                    "y":"566.0"
                },
                "name":"lvp"
            },
            {
                "jdipNS:UNIT":{
                    "x":"514.3",
                    "y":"1055.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"502.79999999999995",
                    "y":"1045.0"
                },
                "name":"lyo"
            },
            {
                "jdipNS:UNIT":{
                    "x":"141.8",
                    "y":"835.3"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"130.3",
                    "y":"825.3"
                },
                "name":"mao"
            },
            {
                "jdipNS:UNIT":{
                    "x":"524.5",
                    "y":"975.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"513.0",
                    "y":"965.0"
                },
                "name":"mar"
            },
            {
                "jdipNS:UNIT":{
                    "x":"126.0",
                    "y":"902.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"114.5",
                    "y":"892.0"
                },
                "name":"mid"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1200.5",
                    "y":"590.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1189.0",
                    "y":"580.0"
                },
                "name":"mos"
            },
            {
                "jdipNS:UNIT":{
                    "x":"693.5",
                    "y":"828.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"682.0",
                    "y":"818.0"
                },
                "name":"mun"
            },
            {
                "jdipNS:UNIT":{
                    "x":"325.5",
                    "y":"1281.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"314.0",
                    "y":"1271.0"
                },
                "name":"naf"
            },
            {
                "jdipNS:UNIT":{
                    "x":"180.1",
                    "y":"288.2"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"168.6",
                    "y":"278.2"
                },
                "name":"nao"
            },
            {
                "jdipNS:UNIT":{
                    "x":"806.5",
                    "y":"1170.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"795.0",
                    "y":"1160.0"
                },
                "name":"nap"
            },
            {
                "jdipNS:UNIT":{
                    "x":"238.0",
                    "y":"427.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"226.5",
                    "y":"417.0"
                },
                "name":"nat"
            },
            {
                "jdipNS:UNIT":{
                    "x":"605.0",
                    "y":"250.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"593.5",
                    "y":"240.0"
                },
                "name":"nrg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"553.5",
                    "y":"560.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"542.0",
                    "y":"550.0"
                },
                "name":"nth"
            },
            {
                "jdipNS:UNIT":{
                    "x":"652.7",
                    "y":"181.8"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"641.2",
                    "y":"171.8"
                },
                "name":"nwg"
            },
            {
                "jdipNS:UNIT":{
                    "x":"703.5",
                    "y":"410.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"692.0",
                    "y":"400.0"
                },
                "name":"nwy"
            },
            {
                "jdipNS:UNIT":{
                    "x":"488.5",
                    "y":"845.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"477.0",
                    "y":"835.0"
                },
                "name":"par"
            },
            {
                "jdipNS:UNIT":{
                    "x":"523.5",
                    "y":"781.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"512.0",
                    "y":"771.0"
                },
                "name":"pic"
            },
            {
                "jdipNS:UNIT":{
                    "x":"630.5",
                    "y":"968.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"619.0",
                    "y":"958.0"
                },
                "name":"pie"
            },
            {
                "jdipNS:UNIT":{
                    "x":"181.5",
                    "y":"1013.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"170.0",
                    "y":"1003.0"
                },
                "name":"por"
            },
            {
                "jdipNS:UNIT":{
                    "x":"865.5",
                    "y":"690.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"854.0",
                    "y":"680.0"
                },
                "name":"pru"
            },
            {
                "jdipNS:UNIT":{
                    "x":"731.5",
                    "y":"1102.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"720.0",
                    "y":"1092.0"
                },
                "name":"rom"
            },
            {
                "jdipNS:UNIT":{
                    "x":"636.5",
                    "y":"779.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"625.0",
                    "y":"769.0"
                },
                "name":"ruh"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1096.5",
                    "y":"967.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1085.0",
                    "y":"957.0"
                },
                "name":"rum"
            },
            {
                "jdipNS:UNIT":{
                    "x":"933.5",
                    "y":"1050.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"922.0",
                    "y":"1040.0"
                },
                "name":"ser"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1284.5",
                    "y":"845.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1273.0",
                    "y":"835.0"
                },
                "name":"sev"
            },
            {
                "jdipNS:UNIT":{
                    "x":"832.5",
                    "y":"769.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"821.0",
                    "y":"759.0"
                },
                "name":"sil"
            },
            {
                "jdipNS:UNIT":{
                    "x":"735.5",
                    "y":"518.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"724.0",
                    "y":"508.0"
                },
                "name":"ska"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1253.5",
                    "y":"1210.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1242.0",
                    "y":"1200.0"
                },
                "name":"smy"
            },
            {
                "jdipNS:UNIT":{
                    "x":"335.5",
                    "y":"1039.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"324.0",
                    "y":"1029.0"
                },
                "name":"spa"
            },
            {
                "jdipNS:UNIT":{
                    "x":"289.0",
                    "y":"965.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"277.5",
                    "y":"955.0"
                },
                "name":"spa-nc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"291.0",
                    "y":"1166.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"279.5",
                    "y":"1156.0"
                },
                "name":"spa-sc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1166.5",
                    "y":"405.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1155.0",
                    "y":"395.0"
                },
                "name":"stp"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1218.0",
                    "y":"222.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1206.5",
                    "y":"212.0"
                },
                "name":"stp-nc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1066.0",
                    "y":"487.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1054.5",
                    "y":"477.0"
                },
                "name":"stp-sc"
            },
            {
                "jdipNS:UNIT":{
                    "x":"829.5",
                    "y":"459.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"818.0",
                    "y":"449.0"
                },
                "name":"swe"
            },
            {
                "jdipNS:UNIT":{
                    "x":"642.0",
                    "y":"928.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"630.5",
                    "y":"918.0"
                },
                "name":"swi"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1452.5",
                    "y":"1206.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1441.0",
                    "y":"1196.0"
                },
                "name":"syr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"825.5",
                    "y":"996.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"814.0",
                    "y":"986.0"
                },
                "name":"tri"
            },
            {
                "jdipNS:UNIT":{
                    "x":"622.5",
                    "y":"1300.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"611.0",
                    "y":"1290.0"
                },
                "name":"tun"
            },
            {
                "jdipNS:UNIT":{
                    "x":"686.5",
                    "y":"1034.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"675.0",
                    "y":"1024.0"
                },
                "name":"tus"
            },
            {
                "jdipNS:UNIT":{
                    "x":"720.0",
                    "y":"1160.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"708.5",
                    "y":"1150.0"
                },
                "name":"tyn"
            },
            {
                "jdipNS:UNIT":{
                    "x":"742.5",
                    "y":"904.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"731.0",
                    "y":"894.0"
                },
                "name":"tyr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"698.5",
                    "y":"1149.1"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"687.0",
                    "y":"1139.1"
                },
                "name":"tys"
            },
            {
                "jdipNS:UNIT":{
                    "x":"1124.5",
                    "y":"800.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"1113.0",
                    "y":"790.0"
                },
                "name":"ukr"
            },
            {
                "jdipNS:UNIT":{
                    "x":"707.5",
                    "y":"994.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"696.0",
                    "y":"984.0"
                },
                "name":"ven"
            },
            {
                "jdipNS:UNIT":{
                    "x":"855.5",
                    "y":"864.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"844.0",
                    "y":"854.0"
                },
                "name":"vie"
            },
            {
                "jdipNS:UNIT":{
                    "x":"428.5",
                    "y":"658.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"417.0",
                    "y":"648.0"
                },
                "name":"wal"
            },
            {
                "jdipNS:UNIT":{
                    "x":"983.5",
                    "y":"740.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"972.0",
                    "y":"730.0"
                },
                "name":"war"
            },
            {
                "jdipNS:UNIT":{
                    "x":"462.5",
                    "y":"1163.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"451.0",
                    "y":"1153.0"
                },
                "name":"wes"
            },
            {
                "jdipNS:UNIT":{
                    "x":"492.5",
                    "y":"616.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"481.0",
                    "y":"606.0"
                },
                "name":"yor"
            }
        ]
    }
};
            