/**
==============================================================================
Copyright (C) 2019 - Philip Paquette, Steven Bocco

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License along
 with this program.  If not, see <https:www.gnu.org/licenses/>.
==============================================================================
**/
export const SvgPureExtra = {
    "jdipNS:DISPLAY":{
        "jdipNS:ZOOM":{
            "min":"5",
            "max":"1000",
            "factor":"1.2"
        },
        "jdipNS:LABELS":{
            "brief":"false",
            "full":"false"
        }
    },
    "jdipNS:ORDERDRAWING":{
        "jdipNS:POWERCOLORS":{
            "jdipNS:POWERCOLOR":[
                {
                    "power":"austria",
                    "color":"#DA251D"
                },
                {
                    "power":"england",
                    "color":"#2D77B2"
                },
                {
                    "power":"france",
                    "color":"#8E85B7"
                },
                {
                    "power":"germany",
                    "color":"#666666"
                },
                {
                    "power":"italy",
                    "color":"#40A340"
                },
                {
                    "power":"russia",
                    "color":"#EEF0E9"
                },
                {
                    "power":"turkey",
                    "color":"#E9F507"
                }
            ]
        },
        "jdipNS:SYMBOLSIZE":[
            {
                "name":"Fleet",
                "width":"40",
                "height":"40"
            },
            {
                "name":"Army",
                "width":"40",
                "height":"40"
            },
            {
                "name":"Wing",
                "width":"40",
                "height":"40"
            },
            {
                "name":"DislodgedFleet",
                "width":"40",
                "height":"40"
            },
            {
                "name":"DislodgedArmy",
                "width":"40",
                "height":"40"
            },
            {
                "name":"DislodgedWing",
                "width":"40",
                "height":"40"
            },
            {
                "name":"FailedOrder",
                "width":"30",
                "height":"30"
            },
            {
                "name":"SupplyCenter",
                "width":"20",
                "height":"20"
            },
            {
                "name":"BuildUnit",
                "width":"60",
                "height":"60"
            },
            {
                "name":"RemoveUnit",
                "width":"50",
                "height":"50"
            },
            {
                "name":"WaivedBuild",
                "width":"40",
                "height":"40"
            }
        ],
        "jdipNS:BUILD":{
            "deltaRadius":"0"
        },
        "jdipNS:REMOVE":{
            "deltaRadius":"5"
        },
        "jdipNS:DISBAND":{
            "deltaRadius":"5"
        },
        "jdipNS:WAIVE":{
            "deltaRadius":"0"
        },
        "jdipNS:HOLD":{
            "deltaRadius":"5",
            "strokeCSSStyle":"varwidthorder",
            "highlightOffset":"0",
            "highlightCSSClass":"varwidthshadow",
            "widths":"5,8,11,14",
            "shadowWidths":"9,12,15,18"
        },
        "jdipNS:MOVE":{
            "deltaRadius":"5",
            "strokeCSSStyle":"varwidthorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"varwidthshadow",
            "widths":"5,8,11,14",
            "shadowWidths":"9,12,15,18"
        },
        "jdipNS:RETREAT":{
            "deltaRadius":"5",
            "strokeCSSStyle":"defaultorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"shadoworder"
        },
        "jdipNS:SUPPORT":{
            "deltaRadius":"10",
            "strokeCSSStyle":"supportorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"shadowdash"
        },
        "jdipNS:CONVOY":{
            "deltaRadius":"10",
            "strokeCSSStyle":"convoyorder",
            "markerID":"arrow",
            "highlightOffset":"0",
            "highlightCSSClass":"shadowdash"
        }
    },
    "jdipNS:PROVINCE_DATA":{
        "jdipNS:PROVINCE":[
            {
                "jdipNS:UNIT":{
                    "x":"762",
                    "y":"205"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"777",
                    "y":"190"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"664",
                    "y":"149"
                },
                "name":"vie"
            },
            {
                "jdipNS:UNIT":{
                    "x":"890",
                    "y":"524"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"905",
                    "y":"509"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"874",
                    "y":"404"
                },
                "name":"lon"
            },
            {
                "jdipNS:UNIT":{
                    "x":"719",
                    "y":"825"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"734",
                    "y":"810"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"800",
                    "y":"734"
                },
                "name":"par"
            },
            {
                "jdipNS:UNIT":{
                    "x":"374",
                    "y":"874"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"389",
                    "y":"859"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"497",
                    "y":"885"
                },
                "name":"ber"
            },
            {
                "jdipNS:UNIT":{
                    "x":"128",
                    "y":"638"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"143",
                    "y":"623"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"193",
                    "y":"738"
                },
                "name":"rom"
            },
            {
                "jdipNS:UNIT":{
                    "x":"152",
                    "y":"299"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"167",
                    "y":"384"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"119",
                    "y":"409"
                },
                "name":"mos"
            },
            {
                "jdipNS:UNIT":{
                    "x":"424",
                    "y":"108"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"439",
                    "y":"93"
                },
                "jdipNS:SUPPLY_CENTER":{
                    "x":"331",
                    "y":"147"
                },
                "name":"con"
            }
        ]
    }
};
            