/**
==============================================================================
Copyright (C) 2019 - Philip Paquette, Steven Bocco

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, either version 3 of the License, or (at your option) any
 later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License along
 with this program.  If not, see <https:www.gnu.org/licenses/>.
==============================================================================
**/
export const SvgPureExtra = {
    "jdipNS:DISPLAY":{
        "jdipNS:ZOOM":{
            "min":"5",
            "max":"1000",
            "factor":"1.2"
        },
        "jdipNS:LABELS":{
            "brief":"false",
            "full":"false"
        }
    },
    "jdipNS:ORDERDRAWING":{
        "jdipNS:POWERCOLORS":{
            "jdipNS:POWERCOLOR":[
                {
                    "power":"austria",
                    "color":"#DA251D"
                },
                {
                    "power":"england",
                    "color":"#2D77B2"
                },
                {
                    "power":"france",
                    "color":"#8E85B7"
                },
                {
                    "power":"germany",
                    "color":"#666666"
                },
                {
                    "power":"italy",
                    "color":"#40A340"
                },
                {
                    "power":"russia",
                    "color":"#EEF0E9"
                },
                {
                    "power":"turkey",
                    "color":"#E9F507"
                }
            ]
        },
        "jdipNS:SYMBOLSIZE":[
            {
                "name":"Fleet",
                "width":"40",
                "height":"40"
            },
            {
                "name":"Army",
                "width":"40",
                "height":"40"
            },
            {
                "name":"Wing",
                "width":"40",
                "height":"40"
            },
            {
                "name":"DislodgedFleet",
                "width":"40",
                "height":"40"
            },
            {
                "name":"DislodgedArmy",
                "width":"40",
                "height":"40"
            },
            {
                "name":"DislodgedWing",
                "width":"40",
                "height":"40"
            },
            {
                "name":"FailedOrder",
                "width":"30",
                "height":"30"
            },
            {
                "name":"SupplyCenter",
                "width":"20",
                "height":"20"
            },
            {
                "name":"BuildUnit",
                "width":"60",
                "height":"60"
            },
            {
                "name":"RemoveUnit",
                "width":"50",
                "height":"50"
            },
            {
                "name":"WaivedBuild",
                "width":"40",
                "height":"40"
            },
            {
                "name":"HoldUnit",
                "width":"66.6",
                "height":"66.6"
            },
            {
                "name":"SupportHoldUnit",
                "width":"76.6",
                "height":"76.6"
            },
            {
                "name":"ConvoyTriangle",
                "width":"66.4",
                "height":"57.4"
            },
            {
                "name":"Stroke",
                "width":"6",
                "height":"10"
            }
        ]
    },
    "jdipNS:PROVINCE_DATA":{
        "jdipNS:PROVINCE":[
            {
                "jdipNS:UNIT":{
                    "x":"362.5",
                    "y":"864.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"374.5",
                    "y":"852.0"
                },
                "name":"ber"
            },
            {
                "jdipNS:UNIT":{
                    "x":"412.5",
                    "y":"98.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"424.5",
                    "y":"86.0"
                },
                "name":"con"
            },
            {
                "jdipNS:UNIT":{
                    "x":"878.5",
                    "y":"514.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"890.5",
                    "y":"502.0"
                },
                "name":"lon"
            },
            {
                "jdipNS:UNIT":{
                    "x":"140.5",
                    "y":"289.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"152.5",
                    "y":"277.0"
                },
                "name":"mos"
            },
            {
                "jdipNS:UNIT":{
                    "x":"707.5",
                    "y":"815.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"719.5",
                    "y":"803.0"
                },
                "name":"par"
            },
            {
                "jdipNS:UNIT":{
                    "x":"116.5",
                    "y":"628.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"128.5",
                    "y":"616.0"
                },
                "name":"rom"
            },
            {
                "jdipNS:UNIT":{
                    "x":"750.5",
                    "y":"195.0"
                },
                "jdipNS:DISLODGED_UNIT":{
                    "x":"762.5",
                    "y":"183.0"
                },
                "name":"vie"
            }
        ]
    }
};
            